using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
namespace Purrington.Domain {
public sealed partial class HotelModel {
 public HotelState State{get;private set;}=new HotelState();public ParityContent Content{get;private set;}public event Action Changed;readonly ISaveStore store;readonly HotelState seed;string recoveryError;public bool RequiresSaveRecovery=>recoveryError!=null; public int Revision{get;private set;}
 sealed class Edit{public HotelState before,after;public double cost;}readonly List<Edit> undo=new List<Edit>(),redo=new List<Edit>();
 public HotelModel(ISaveStore store,ParityContent content){this.store=store??throw new ArgumentNullException(nameof(store));Content=content??throw new ArgumentNullException(nameof(content));seed=content.CreateState();}
 public HotelModel(ISaveStore store,HotelState authoredSeed=null){this.store=store??throw new ArgumentNullException(nameof(store));Content=ParityContent.Current;seed=authoredSeed==null?(Content?.CreateState()??new HotelState()):Copy(authoredSeed);}
 public HotelData Hotel(int index=-1){return State.hotels[index<0?State.currentHotel:index];} public JObject Map(int index=-1){return Content.Maps[index<0?State.currentHotel:index];}
 public CommandResult LoadOrCreate(){HotelState loaded=null;recoveryError=null;try{loaded=store.Load();ShellMigration.Upgrade(loaded);}catch{recoveryError="Your save could not be read. Original files are preserved.";}if(store is ISaveStatus status&&status.HasExistingSave&&loaded==null)recoveryError=status.LoadError??"Saved hotel needs recovery.";if(loaded!=null&&!Valid(loaded))recoveryError="Saved hotel is invalid. Original files are preserved.";State=Copy(loaded!=null&&Valid(loaded)?loaded:seed);undo.Clear();redo.Clear();Invalidate();ResetLife();Changed?.Invoke();return recoveryError!=null?CommandResult.Fail(recoveryError):loaded==null?Save():CommandResult.Ok("Welcome back!");}
 public CommandResult RetrySave(){return RequiresSaveRecovery?LoadOrCreate():Save();}public CommandResult Save(){return TrySave()?CommandResult.Ok("Hotel saved."):CommandResult.Fail(recoveryError??"Couldn't save right now. Your progress is still here — tap Retry.");}bool TrySave(){if(recoveryError!=null)return false;long old=State.lastSeen;try{State.lastSeen=DateTimeOffset.UtcNow.ToUnixTimeSeconds();if(store.Save(Copy(State)))return true;State.lastSeen=old;return false;}catch{State.lastSeen=old;return false;}}
 public static HotelState Copy(HotelState s){return JsonConvert.DeserializeObject<HotelState>(JsonConvert.SerializeObject(s));}
 void Invalidate(){Revision++;navCache.Clear();venueCache.Clear();statusCache.Clear();}
 public CommandResult Quote(string action,JObject payload){var before=State;State=Copy(State);try{return Apply(action,payload??new JObject());}catch(Exception e)when(e is ArgumentException||e is InvalidCastException||e is FormatException||e is OverflowException){return CommandResult.Fail("Choose valid values for this action.");}finally{State=before;}}
 public CommandResult Execute(string action,JObject payload){if(action=="collect")return ClaimOffline();if(action=="playdate")return Playdate((int?)payload["cat"]??-1,(int?)payload["other"]??-1);var before=Copy(State);CommandResult r;try{r=Apply(action,payload??new JObject());}catch(Exception e)when(e is ArgumentException||e is InvalidCastException||e is FormatException||e is OverflowException){r=CommandResult.Fail("Choose valid values for this action.");}if(!r.success){State=before;return r;}State.coins-=r.cost;if(!TrySave()){State=before;Invalidate();return CommandResult.Fail("Couldn't save — nothing changed, and your coins are safe. Tap Retry.");}undo.Add(new Edit{before=before,after=Copy(State),cost=r.cost});if(undo.Count>20)undo.RemoveAt(0);redo.Clear();Invalidate();Changed?.Invoke();return r;}
 double Price(double p){return State.settings.godMode?0:p;}static double Shell(RoomState r){double a=r.width*r.depth;return r.kind=="regular"?450+Math.Max(0,a-12)*25:r.kind=="suite"?1200+Math.Max(0,a-20)*25:a*25;}string Id(string p){return p+State.nextId++;}
 static bool Whole(JToken t){return t!=null&&(t.Type==JTokenType.Integer||t.Type==JTokenType.Float)&&double.TryParse(t.ToString(),out double n)&&!double.IsNaN(n)&&!double.IsInfinity(n)&&n==Math.Floor(n);}
 static bool RoomShape(RoomState r){return new[]{"regular","suite","shared","terrace"}.Contains(r.kind)&&r.width>=(r.kind=="regular"||r.kind=="suite"?4:2)&&r.depth>=(r.kind=="suite"?5:r.kind=="regular"?3:2)&&r.width<=80&&r.depth<=80&&r.rotation>=0&&r.rotation<4;}
 CommandResult Apply(string action,JObject p){foreach(string field in new[]{"rotation","w","h","service","staff","floor"})if(p[field]!=null&&!Whole(p[field]))return CommandResult.Fail("Choose whole grid dimensions and valid levels.");var h=Hotel();double cost=0;string message="Saved";var displaced=new List<string>();string id=(string)p["id"]??"";RoomState r=null;ObjectState o;
 var editedRoom=h.rooms.Find(v=>v.id==id);bool wasInterior=editedRoom!=null&&Interior(h,editedRoom);double oldFit=editedRoom!=null?Fitting(editedRoom):0,oldPaid=editedRoom?.paid??0;
 switch(action){
 case "buy_plot":var plot=Map()["plots"].FirstOrDefault(t=>(string)t["id"]==id);if(plot==null||h.plots.Contains(id))return CommandResult.Fail("Choose land you do not own yet.");h.plots.Add(id);cost=(double)plot["cost"];message=(string)plot["name"]+" is yours";break;
 case "place_room":if(!Whole(p["x"])||!Whole(p["y"]))return CommandResult.Fail("Place the room on the grid.");r=new RoomState{id=Id("room"),kind=(string)p["kind"]??"regular",name=(string)p["name"]??"New room",x=(int)p["x"],z=(int)p["y"],width=(int?)p["w"]??4,depth=(int?)p["h"]??3,rotation=(int?)p["rotation"]??0,floor=(int?)p["floor"]??0};if(!RoomShape(r))return CommandResult.Fail("Regular rooms start at 4 × 3; suites at 4 × 5.");r.paid=cost=Price(Interior(h,r)?Fitting(r):Shell(r));h.rooms.Add(r);break;
 case "remove_room":case "move_room":case "copy_room":case "resize_room":r=h.rooms.Find(v=>v.id==id);if(r==null)return CommandResult.Fail("Select an existing room.");var old=JsonConvert.DeserializeObject<RoomState>(JsonConvert.SerializeObject(r));var children=h.objects.Where(v=>v.room==id).ToArray();if(action=="remove_room"){cost=-r.paid;foreach(var c in children){h.objects.Remove(c);State.storage.Add(c);}h.rooms.Remove(r);break;}if(action=="resize_room"){if(!Whole(p["w"])||!Whole(p["h"]))return CommandResult.Fail("Choose whole room dimensions.");r.width=(int)p["w"];r.depth=(int)p["h"];if(!RoomShape(r))return CommandResult.Fail("Keep minimum room dimensions.");double diff=(r.width*r.depth-old.width*old.depth)*25;cost=diff>0?Price(diff):-Math.Min(old.paid,-diff);r.paid+=cost;foreach(var c in children)if(!Rect(r).Encloses(Rect(c))){displaced.Add(Catalog.Find(c.itemId).name);h.objects.Remove(c);State.storage.Add(c);}break;}if(!Whole(p["x"])||!Whole(p["y"]))return CommandResult.Fail("Choose a room position on the grid.");if(action=="copy_room"){r=JsonConvert.DeserializeObject<RoomState>(JsonConvert.SerializeObject(old));r.id=Id("room");r.name="Copy of "+old.name;r.paid=cost=Price(Shell(r));h.rooms.Add(r);}r.x=(int)p["x"];r.z=(int)p["y"];r.rotation=(int?)p["rotation"]??r.rotation;foreach(var child in children){o=action=="copy_room"?JsonConvert.DeserializeObject<ObjectState>(JsonConvert.SerializeObject(child)):child;TransformObject(o,Rect(old),Rect(r),r.rotation-old.rotation);o.room=r.id;if(action=="copy_room"){o.id=Id("object");o.paid=Price(Catalog.Find(o.itemId).price);cost+=o.paid;h.objects.Add(o);}}break;
 case "place_template":var template=Content.Templates.FirstOrDefault(t=>(string)t["id"]==(string)p["template"]);if(template==null)return CommandResult.Fail("Choose an arrangement.");if(!Whole(p["x"])||!Whole(p["y"]))return CommandResult.Fail("Place the arrangement on the grid.");r=new RoomState{id=Id("space"),kind=(string)template["kind"],name=(string)template["name"],x=(int)p["x"],z=(int)p["y"],width=(int)template["w"],depth=(int)template["h"],rotation=(int?)p["rotation"]??0};r.paid=cost=Price(r.width*r.depth*25);h.rooms.Add(r);foreach(var raw in template["objects"]){o=ParityContent.ReadObject(raw);o.id=Id("object");o.room=r.id;o.paid=Price(Catalog.Find(o.itemId).price);TransformObject(o,new LotRect(0,0,r.width,r.depth),Rect(r),r.rotation);cost+=o.paid;h.objects.Add(o);}break;
 case "place_object":case "move_object":case "retrieve_object":case "store_object":if(action=="place_object"){var item=Catalog.Find((string)p["item"]);if(item==null)return CommandResult.Fail("Choose catalogue furniture.");if(!State.settings.godMode&&item.bond>0&&!State.cats.Any(c=>c.known&&c.bond>=item.bond))return CommandResult.Fail("Reach 20 friendship to unlock this blanket.");cost=Price(item.price);o=new ObjectState{id=Id("object"),itemId=item.id,paid=cost};h.objects.Add(o);}else{o=(action=="retrieve_object"?State.storage:h.objects).Find(v=>v.id==id);if(o==null)return CommandResult.Fail("Select owned furniture.");}if(action=="store_object"){h.objects.Remove(o);o.room="";State.storage.Add(o);}else{if(p["x"]==null||p["y"]==null)return CommandResult.Fail("Choose a furniture position.");o.x=(float)p["x"];o.z=(float)p["y"];o.rotation=(int?)p["rotation"]??0;if(action=="retrieve_object"){State.storage.Remove(o);h.objects.Add(o);}}break;
 case "paint_path":case "erase_path":string style=(string)p["style"]??"earth";if(!new[]{"earth","gravel","brick"}.Contains(style))return CommandResult.Fail("Choose earth, gravel or brick.");if(!(p["cells"] is JArray cells)||cells.Count>10000)return CommandResult.Fail("Draw a path on your lot.");var visited=new HashSet<string>();foreach(var cell in cells){if(!(cell is JArray pair)||pair.Count!=2||!Whole(pair[0])||!Whole(pair[1]))return CommandResult.Fail("Draw paths on whole cells.");int x=(int)pair[0],z=(int)pair[1];string key=x+","+z;if(!visited.Add(key))continue;if(!Owns(new LotRect(x,z,1,1),State.currentHotel))return CommandResult.Fail("Paths must stay on owned land.");h.paths.TryGetValue(key,out var prior);if(action=="erase_path"){cost-=prior?.paid??0;h.paths.Remove(key);}else if(prior?.style!=style){double price=Price(style=="earth"?2:style=="gravel"?4:6);cost+=price-(prior?.paid??0);h.paths[key]=new PathState{style=style,paid=price};}}break;
 case "upgrade":case "upgrade_service":int service=(int?)p["service"]??-1;if(service<0||service>3||h.upgrades[service]>=10)return CommandResult.Fail("This service is fully upgraded.");cost=Math.Round(240*Math.Pow(2,h.upgrades[service]/3.0),MidpointRounding.AwayFromZero);h.upgrades[service]++;h.purchases++;h.level=Math.Min(10,1+h.purchases/2);break;
 case "train":case "hire_staff":int staff=(int?)p["staff"]??-1;if(staff<0||staff>2||h.staff[staff]>=3)return CommandResult.Fail("This staff member is fully trained.");cost=250*(++h.staff[staff]);break;
 case "hire_housekeeper":case "hire_maid":if(h.maid)return CommandResult.Fail("Daisy already works here.");if(h.level<3&&!State.settings.godMode)return CommandResult.Fail("Housekeeping opens at level 3.");cost=600;h.maid=true;message="Daisy will look after your guest rooms";break;
 case "draw_room":{int level=(int?)p["floor"]??0;if(!Whole(p["x"])||!Whole(p["y"]))return CommandResult.Fail("Draw the room on the grid.");var drawn=new RoomState{kind=(string)p["kind"]??"regular",x=(int)p["x"],z=(int)p["y"],width=(int?)p["w"]??4,depth=(int?)p["h"]??3,rotation=(int?)p["rotation"]??0,floor=level};if(!IndoorKind(drawn.kind))return CommandResult.Fail("Choose a bedroom, suite or lounge.");if(!RoomShape(drawn))return CommandResult.Fail("Regular rooms start at 4 × 3; suites at 4 × 5.");RoomCells(drawn,out int dx,out int dz,out int dw,out int dd);var floorCells=Floor(h,level,true);var missing=Enumerable.Range(0,dw*dd).Select(i=>(x:dx+i%dw,z:dz+i/dw)).Where(c=>!floorCells.cells.ContainsKey(ShellGrid.Cell(c.x,c.z))).ToList();double grown=0;if(missing.Count>0){var painted=PaintCells(h,level,missing,(bool?)p["buy"]??false);if(!painted.success)return painted;grown=painted.cost;}var placed=Apply("place_room",p);if(!placed.success)return placed;cost=grown+placed.cost;message="Room added";break;}
 case "paint_floor":case "erase_floor":case "set_edge":var shell=ApplyShell(action,p,h);if(!shell.success)return shell;cost=shell.cost;message=shell.message;break;
 default:return CommandResult.Fail("Choose a building action.");}
 if(wasInterior&&r!=null&&(action=="move_room"||action=="resize_room")){RoomCells(r,out int gx,out int gz,out int gw,out int gd);var gf=Floor(h,r.floor,true);var gaps=Enumerable.Range(0,gw*gd).Select(i=>(x:gx+i%gw,z:gz+i/gw)).Where(c=>!gf.cells.ContainsKey(ShellGrid.Cell(c.x,c.z))).ToList();if(gaps.Count>0){var tiles=PaintCells(h,r.floor,gaps,false);if(!tiles.success)return tiles;cost+=tiles.cost;}}if(action=="resize_room"&&wasInterior&&r!=null&&Interior(h,r)){double delta=Fitting(r)-oldFit,change=delta>0?Price(delta):-Math.Min(oldPaid,-delta);cost+=change-(r.paid-oldPaid);r.paid=oldPaid+change;}if(action=="move_room"&&!wasInterior&&r!=null&&Interior(h,r)){double fit=Price(Fitting(r));if(fit<r.paid){cost+=fit-r.paid;r.paid=fit;}}if(action=="copy_room"&&r!=null&&Interior(h,r)){double fit=Price(Fitting(r));cost+=fit-r.paid;r.paid=fit;}
 SyncRoomWalls(h);if(State.settings.godMode)cost=0;var valid=ValidateLayout(State.currentHotel);if(!valid.success)return valid;valid=ValidateShell(State.currentHotel);if(!valid.success)return valid;if(State.coins+.0001<cost)return CommandResult.Fail("Need "+Math.Ceiling(cost-State.coins)+" more Cat Coins.");var result=CommandResult.Ok(message,cost);result.displaced=displaced;return result;}
 static void TransformObject(ObjectState o,LotRect from,LotRect to,int turns){var a=Rect(o);float x=a.x+a.w/2-from.x-from.w/2,z=a.z+a.d/2-from.z-from.d/2;turns=(turns%4+4)%4;for(int n=0;n<turns;n++){float t=x;x=-z;z=t;}o.rotation=(o.rotation+turns)%4;Size(o,out float w,out float d);o.x=(float)Math.Round((to.x+to.w/2+x-w/2)*2)/2;o.z=(float)Math.Round((to.z+to.d/2+z-d/2)*2)/2;}
 public CommandResult Undo(){return Replay(undo,redo,true);}public CommandResult Redo(){return Replay(redo,undo,false);}CommandResult Replay(List<Edit> from,List<Edit> to,bool reverse){if(from.Count==0)return CommandResult.Fail("Nothing to "+(reverse?"undo.":"redo."));var e=from[from.Count-1];if(!JToken.DeepEquals(BuildSnapshot(State),BuildSnapshot(reverse?e.after:e.before)))return CommandResult.Fail("The building changed since this action.");double cost=reverse?-e.cost:e.cost;if(State.coins<cost)return CommandResult.Fail("Not enough Cat Coins.");var before=Copy(State);var layout=Copy(reverse?e.before:e.after);for(int i=0;i<State.hotels.Count;i++){var h=Hotel(i);var b=layout.hotels[i];h.rooms=b.rooms;h.floors=b.floors;h.objects=b.objects;h.plots=b.plots;h.paths=b.paths;h.upgrades=b.upgrades;h.staff=b.staff;h.level=b.level;h.purchases=b.purchases;h.maid=b.maid;}State.storage=layout.storage;State.coins-=cost;if(!TrySave()){State=before;return CommandResult.Fail("Couldn't save — nothing changed. Tap Retry.");}from.RemoveAt(from.Count-1);to.Add(e);Invalidate();Changed?.Invoke();return CommandResult.Ok(reverse?"Undone":"Redone",cost);}
 static JToken BuildSnapshot(HotelState s){return JToken.FromObject(new{hotels=s.hotels.Select(h=>new{h.rooms,h.floors,h.objects,h.paths,h.plots,h.upgrades,h.staff,h.level,h.purchases,h.maid}).ToArray(),s.storage});} CommandResult Transaction(Action apply,string message){var before=Copy(State);apply();if(!TrySave()){State=before;return CommandResult.Fail("Couldn't save — nothing changed. Tap Retry.");}Changed?.Invoke();return CommandResult.Ok(message);}
 public CommandResult Care(int catId,string tool){tool=(tool??"").ToLowerInvariant();if(tool=="feather")tool="wand";if(!new[]{"pet","brush","wand","yarn","cushion","box"}.Contains(tool))return CommandResult.Fail("Choose a care tool.");var c=State.cats.Find(v=>v.id==catId&&v.known);if(c==null)return CommandResult.Fail("Meet this cat first.");if(c.bond>=100||State.elapsed-c.lastCare<12)return CommandResult.Ok(c.name+" is enjoying your company.");int gain=c.favoriteAction==tool?6:3;var r=Transaction(()=>{c.bond=Math.Min(100,c.bond+gain);c.lastCare=State.elapsed;},c.name+" loved that! +"+gain+" friendship");r.progressChanged=r.success;return r;}
 public CommandResult SetAssistedCare(bool enabled){return Transaction(()=>State.settings.assistedCare=enabled,"Assisted care "+(enabled?"on":"off"));}
 public CommandResult SetSettings(float textScale,bool motion,bool music,bool sound){return SetSettings(textScale,motion,music,sound,State.settings.exterior,State.settings.evening);}public CommandResult SetSettings(float textScale,bool motion,bool music,bool sound,bool exterior,bool evening){if(textScale<1||textScale>1.5||float.IsNaN(textScale))return CommandResult.Fail("Choose a text size from 100% to 150%.");return Transaction(()=>{State.settings.textScale=textScale;State.settings.motion=motion;State.settings.music=music;State.settings.sound=sound;State.settings.exterior=exterior;State.settings.evening=evening;},"Settings saved.");}
 public CommandResult SetGodMode(bool enabled){if(State.settings.godMode==enabled)return CommandResult.Ok("God mode is already "+(enabled?"on":"off"));var r=Transaction(()=>{State.settings.godMode=enabled;if(enabled){for(int i=0;i<4;i++){Hotel(i).owned=true;Hotel(i).plots=Map(i)["plots"].Select(p=>(string)p["id"]).ToList();}foreach(var c in State.cats)c.known=true;State.entitlements=new List<string>{"purrington.cat_club","purrington.forest_lodge","purrington.snowcap_spa"};}},"God mode "+(enabled?"on":"off"));if(r.success){undo.Clear();redo.Clear();Invalidate();ResetLife();}return r;}
 public CommandResult CanTravel(int index){if(index<0||index>3)return CommandResult.Fail("Choose a destination.");if(State.settings.godMode)return CommandResult.Ok("God mode · visit "+(string)Map(index)["name"]);if(Hotel(index).owned)return CommandResult.Ok("Visit "+(string)Map(index)["name"]);if(index==1){const double seasideCost=10000;if(Hotel(0).level<10)return CommandResult.Fail("Reach Meadow level 10 and save 10,000 Cat Coins",seasideCost);return State.coins>=seasideCost?CommandResult.Ok("Open Seaside Suites · 10,000",seasideCost):CommandResult.Fail("Open Seaside Suites · 10,000",seasideCost);}return State.entitlements.Contains(index==2?"purrington.forest_lodge":"purrington.snowcap_spa")?CommandResult.Ok("Visit expansion"):CommandResult.Fail("Unlock this preview expansion first.");}
 public CommandResult Travel(int index){var q=CanTravel(index);if(!q.success)return q;var r=Transaction(()=>{State.coins-=q.cost;Hotel(index).owned=true;State.currentHotel=index;},"Welcome to "+(string)Map(index)["name"]);if(r.success){Invalidate();ResetLife();}return r;}
 public CommandResult GrantEntitlement(string id){int[] ids=id=="purrington.cat_club"?new[]{12,13,14}:id=="purrington.forest_lodge"?new[]{16}:id=="purrington.snowcap_spa"?new[]{15,17}:null;if(ids==null)return CommandResult.Fail("Unknown preview product.");return Transaction(()=>{if(!State.entitlements.Contains(id))State.entitlements.Add(id);foreach(int n in ids)State.cats[n].known=true;},"Preview content unlocked.");}
 public CommandResult Playdate(int cat,int other){if(cat==other||cat<0||other<0||cat>=State.cats.Count||other>=State.cats.Count||!State.cats[cat].known||!State.cats[other].known)return CommandResult.Fail("Choose two known cats.");if(!State.settings.godMode&&(State.cats[cat].bond<10||State.cats[other].bond<10))return CommandResult.Fail("Get to know both cats first · 10 friendship each.");if(!Venues().Any(v=>v.open&&v.role=="seat"&&v.service==2))return CommandResult.Fail("Create a reachable social lounge first.");return Transaction(()=>{State.cats[cat].friend=other;State.cats[other].friend=cat;},"Playdate arranged.");}
 public CommandResult Reconcile(long now){if(now<0)return CommandResult.Fail("Invalid clock.");return Transaction(()=>{if(State.lastSeen>0)State.pendingCoins+=Rate()*Math.Min(28800,Math.Max(0,now-State.lastSeen))/60;State.lastSeen=now;},"Offline earnings ready.");}public CommandResult ClaimOffline(){return Transaction(()=>{State.coins+=State.pendingCoins;State.pendingCoins=0;},"Welcome-back coins collected.");}
 public CommandResult Reset(){var old=State;string error=recoveryError;State=Copy(seed);State.lastSeen=DateTimeOffset.UtcNow.ToUnixTimeSeconds();recoveryError=null;bool saved=false;try{saved=store is IResettableSaveStore reset?reset.Reset(Copy(State)):TrySave();}catch{}if(!saved){State=old;recoveryError=error;return CommandResult.Fail("Could not save reset. Your hotel is unchanged.");}undo.Clear();redo.Clear();Invalidate();ResetLife();Changed?.Invoke();return CommandResult.Ok("A fresh hotel is ready.");}
 public double CatalogPrice(string action,JObject p){if(State.settings.godMode)return 0;if(action=="place_object")return Catalog.Find((string)p["item"])?.price??0;if(action=="place_room")return Shell(new RoomState{kind=(string)p["kind"]??"regular",width=(int?)p["w"]??4,depth=(int?)p["h"]??3});if(action=="place_template"){var t=Content.Templates.FirstOrDefault(v=>(string)v["id"]==(string)p["template"]);return t==null?0:(int)t["w"]*(int)t["h"]*25+t["objects"].Sum(o=>Catalog.Find((string)o["item"]).price);}return 0;} static JObject P(params object[] values){var p=new JObject();for(int i=0;i<values.Length;i+=2)p[(string)values[i]]=JToken.FromObject(values[i+1]);return p;}
 public CommandResult PreviewRoom(int x,int z,int width=4,int depth=3){return Quote("place_room",P("x",x,"y",z,"w",width,"h",depth));}public CommandResult PlaceRoom(int x,int z,int width=4,int depth=3){return Execute("place_room",P("x",x,"y",z,"w",width,"h",depth));}
 public CommandResult PreviewObject(string item,float x,float z,int rotation=0){return Quote("place_object",P("item",item,"x",x,"y",z,"rotation",rotation));}public CommandResult PlaceObject(string item,float x,float z,int rotation=0){return Execute("place_object",P("item",item,"x",x,"y",z,"rotation",rotation));}
 public CommandResult PreviewMoveObject(string id,float x,float z,int rotation=0){return Quote("move_object",P("id",id,"x",x,"y",z,"rotation",rotation));}public CommandResult MoveObject(string id,float x,float z,int rotation=0){return Execute("move_object",P("id",id,"x",x,"y",z,"rotation",rotation));}
 public CommandResult PreviewMoveRoom(string id,int x,int z,int rotation=0){return Quote("move_room",P("id",id,"x",x,"y",z,"rotation",rotation));}public CommandResult MoveRoom(string id,int x,int z,int rotation=0){return Execute("move_room",P("id",id,"x",x,"y",z,"rotation",rotation));}
 public CommandResult PreviewRetrieveObject(string id,float x,float z,int rotation=0){return Quote("retrieve_object",P("id",id,"x",x,"y",z,"rotation",rotation));}public CommandResult RetrieveObject(string id,float x,float z,int rotation=0){return Execute("retrieve_object",P("id",id,"x",x,"y",z,"rotation",rotation));}public CommandResult PlaceStoredObject(string id,float x,float z,int rotation=0){return RetrieveObject(id,x,z,rotation);}public CommandResult RemoveObject(string id){return Execute("store_object",P("id",id));}public CommandResult StoreObject(string id){return RemoveObject(id);}public CommandResult RemoveRoom(string id){return Execute("remove_room",P("id",id));}
 public static bool Valid(HotelState s){try{return ValidCore(s);}catch(Exception e)when(e is ArgumentException||e is InvalidOperationException||e is NullReferenceException||e is OverflowException){return false;}} static bool ValidCore(HotelState s){if(s==null||s.version!=3||!Finite(s.coins)||s.coins<0||!Finite(s.elapsed)||s.elapsed<0||s.nextId<1||s.hotels==null||s.hotels.Count!=4||s.currentHotel<0||s.currentHotel>3||!s.hotels[s.currentHotel].owned||s.cats==null||s.cats.Count!=18||s.storage==null||s.settings==null||s.entitlements==null||!Finite(s.pendingCoins)||s.pendingCoins<0||s.lastSeen<0)return false;var ids=new HashSet<string>();foreach(var h in s.hotels){if(h==null||h.rooms==null||h.floors==null||h.floors.Any(f=>f==null||f.cells==null||f.edges==null)||h.objects==null||h.paths==null||h.plots==null||h.upgrades==null||h.upgrades.Length!=4||h.staff==null||h.staff.Length!=3||h.level<1||h.level>10||h.upgrades.Any(v=>v<0||v>10)||h.staff.Any(v=>v<0||v>3)||h.dirty==null)return false;foreach(var r in h.rooms)if(r==null||string.IsNullOrEmpty(r.id)||!RoomShape(r)||!Finite(r.paid)||r.paid<0||r.paid>Shell(r)||Math.Abs(r.x)>256||Math.Abs(r.z)>256)return false;foreach(var o in h.objects.Concat(s.storage)){if(o==null||string.IsNullOrEmpty(o.id)||Catalog.Find(o.itemId)==null||o.rotation<0||o.rotation>3||!Finite(o.paid)||o.paid<0||o.paid>Catalog.Find(o.itemId).price||!Finite(o.x)||!Finite(o.z)||o.x*2!=Math.Floor(o.x*2)||o.z*2!=Math.Floor(o.z*2))return false;}foreach(var o in h.objects)if(!ids.Add(o.id))return false;}foreach(var o in s.storage)if(!ids.Add(o.id))return false;return s.cats.Select((c,i)=>c!=null&&c.id==i&&c.bond>=0&&c.bond<=100&&Finite(c.lastCare)&&!string.IsNullOrEmpty(c.name)).All(v=>v)&&s.settings.textScale>=1&&s.settings.textScale<=1.5&&ValidateContent(s);}
 static bool Finite(double n){return !double.IsNaN(n)&&!double.IsInfinity(n);}
}
}







