using System;using System.Collections.Generic;using System.Linq;using Newtonsoft.Json.Linq;
namespace Purrington.Domain {
public struct LotRect{public float x,z,w,d;public LotRect(float x,float z,float w,float d){this.x=x;this.z=z;this.w=w;this.d=d;}public bool Has(float a,float b){return a>=x&&b>=z&&a<x+w&&b<z+d;}public bool Encloses(LotRect b){return b.x>=x&&b.z>=z&&b.x+b.w<=x+w&&b.z+b.d<=z+d;}public bool Intersects(LotRect b){return x<b.x+b.w&&x+w>b.x&&z<b.z+b.d&&z+d>b.z;}public LotRect Grow(float a){return new LotRect(x-a,z-a,w+2*a,d+2*a);}}
public sealed partial class HotelModel {
 readonly Dictionary<string,Nav> navCache=new Dictionary<string,Nav>();readonly Dictionary<int,List<VenueSnapshot>> venueCache=new Dictionary<int,List<VenueSnapshot>>();
 sealed class Nav{public Dictionary<long,LotPoint> points=new Dictionary<long,LotPoint>();public List<LotRect> solids=new List<LotRect>();public Dictionary<long,List<long>> edges=new Dictionary<long,List<long>>();}
 static long Key(int x,int z){return ((long)x<<32)|(uint)z;}static long Key(LotPoint p){return Key((int)Math.Floor(p.x*2),(int)Math.Floor(p.z*2));}
 public static void RoomSize(RoomState r,out float w,out float d){w=r.rotation%2==0?r.width:r.depth;d=r.rotation%2==0?r.depth:r.width;}public static void Size(ObjectState o,out float w,out float d){var i=Catalog.Find(o.itemId);w=o.rotation%2==0?i?.width??1:i?.depth??1;d=o.rotation%2==0?i?.depth??1:i?.width??1;}
 static LotRect Rect(RoomState r){RoomSize(r,out float w,out float d);return new LotRect(r.x,r.z,w,d);}static LotRect Rect(ObjectState o){Size(o,out float w,out float d);return new LotRect(o.x,o.z,w,d);}static LotRect Rect(JToken t){return new LotRect((float)t[0],(float)t[1],(float)t[2],(float)t[3]);}
 public static void DoorPosition(RoomState r,out float x,out float z){var b=Rect(r);x=b.x+b.w/2;z=b.z+b.d/2;switch(r.rotation){case 0:x=b.x+b.w+.25f;break;case 1:z=b.z+b.d+.25f;break;case 2:x=b.x-.25f;break;case 3:z=b.z-.25f;break;}}
 bool Owned(float x,float z,int index){var map=Map(index);if(Rect(map["base"]).Has(x,z))return true;return map["plots"].Any(p=>Hotel(index).plots.Contains((string)p["id"])&&Rect(p["rect"]).Has(x,z));}
 bool Owns(LotRect r,int index){for(int x=(int)Math.Floor(r.x*2);x<Math.Ceiling((r.x+r.w)*2);x++)for(int z=(int)Math.Floor(r.z*2);z<Math.Ceiling((r.z+r.d)*2);z++)if(!Owned(x*.5f+.25f,z*.5f+.25f,index))return false;return true;}
 CommandResult ValidateLayout(int index){var h=Hotel(index);var roomIds=new HashSet<string>();var objectIds=new HashSet<string>();foreach(var r in h.rooms){if(!RoomShape(r)||!roomIds.Add(r.id)||!Owns(Rect(r),index))return CommandResult.Fail("Keep the whole room on owned land.");if(h.rooms.Any(b=>b!=r&&Rect(b).Intersects(Rect(r))))return CommandResult.Fail("Rooms need their own floor space.");foreach(var s in Map(index)["scenery"]??new JArray())if((bool?)s["protected"]==true&&Rect(r).Intersects(new LotRect((float)s["x"],(float)s["y"],(float?)s["size"]??2,(float?)s["size"]??2)))return CommandResult.Fail("Keep this scenic landmark clear.");}foreach(var o in h.objects){var item=Catalog.Find(o.itemId);if(item==null||!objectIds.Add(o.id)||!Finite(o.x)||!Finite(o.z)||Math.Abs(o.x)>256||Math.Abs(o.z)>256||o.x*2!=Math.Floor(o.x*2)||o.z*2!=Math.Floor(o.z*2)||o.rotation<0||o.rotation>3)return CommandResult.Fail("Choose a valid half-cell furniture position.");var b=Rect(o);if(!Owns(b,index))return CommandResult.Fail("Keep the whole object on owned land.");var room=h.rooms.Find(r=>Rect(r).Encloses(b));if(h.rooms.Any(r=>r!=room&&Rect(r).Intersects(b)))return CommandResult.Fail("Keep furniture inside one space or outside walls.");string surface=room!=null&&room.kind!="terrace"?"indoor":"outdoor";if(!item.surfaces.Contains(surface))return CommandResult.Fail("This item belongs "+(surface=="indoor"?"outside.":"on an indoor floor."));o.room=room?.id??"";if(item.shape!="rug"&&h.objects.Any(other=>other!=o&&Catalog.Find(other.itemId)?.shape!="rug"&&b.Grow(-.01f).Intersects(Rect(other).Grow(-.01f))))return CommandResult.Fail("Leave space between objects.");}return CommandResult.Ok("Ready to place");}
 Nav Graph(bool constructed,int index){string cache=index+":"+constructed;if(navCache.TryGetValue(cache,out var saved))return saved;var n=new Nav();var h=Hotel(index);var bounds=Rect(Map(index)["base"]);foreach(var p in Map(index)["plots"])if(h.plots.Contains((string)p["id"])){var b=Rect(p["rect"]);float right=Math.Max(bounds.x+bounds.w,b.x+b.w),bottom=Math.Max(bounds.z+bounds.d,b.z+b.d);bounds.x=Math.Min(bounds.x,b.x);bounds.z=Math.Min(bounds.z,b.z);bounds.w=right-bounds.x;bounds.d=bottom-bounds.z;}
 foreach(var r in h.rooms){if(r.kind=="terrace")continue;var b=Rect(r);for(int side=0;side<4;side++){bool vertical=side%2==0;float x=side==0?b.x+b.w:b.x,z=side==1?b.z+b.d:b.z,length=vertical?b.d:b.w;if(r.kind=="shared"||r.rotation==side){float first=length*.5f-.8f;n.solids.Add(new LotRect(x,z,vertical?0:first,vertical?first:0).Grow(.18f));n.solids.Add(new LotRect(x+(vertical?0:length*.5f+.8f),z+(vertical?length*.5f+.8f:0),vertical?0:first,vertical?first:0).Grow(.18f));}else n.solids.Add(new LotRect(x,z,vertical?0:length,vertical?length:0).Grow(.18f));}}
 foreach(var o in h.objects){var item=Catalog.Find(o.itemId);if(item.role!="gate"&&item.shape!="rug")n.solids.Add(Rect(o).Grow(.18f));}
 for(int x=(int)(bounds.x*2);x<(bounds.x+bounds.w)*2;x++)for(int z=(int)(bounds.z*2);z<(bounds.z+bounds.d)*2;z++){var p=new LotPoint(x*.5f+.25f,z*.5f+.25f);if(!Owned(p.x,p.z,index)||n.solids.Any(b=>b.Has(p.x,p.z)))continue;if(constructed&&!h.rooms.Any(r=>Rect(r).Has(p.x,p.z))&&!h.paths.ContainsKey((int)Math.Floor(p.x)+","+(int)Math.Floor(p.z)))continue;n.points[Key(x,z)]=p;}
 foreach(var p in n.points){var neighbors=new List<long>();int x=(int)Math.Floor(p.Value.x*2),z=(int)Math.Floor(p.Value.z*2);for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++){if(dx==0&&dz==0)continue;long k=Key(x+dx,z+dz);if(n.points.TryGetValue(k,out var q)&&Segment(p.Value,q,n))neighbors.Add(k);}n.edges[p.Key]=neighbors;}navCache[cache]=n;return n;}
 static bool Hits(LotPoint a,LotPoint b,LotRect r){float enter=0,leave=1;for(int axis=0;axis<2;axis++){float start=axis==0?a.x:a.z,delta=axis==0?b.x-a.x:b.z-a.z,min=axis==0?r.x:r.z,max=min+(axis==0?r.w:r.d);if(Math.Abs(delta)<.000001){if(start<min||start>max)return false;}else{float p=(min-start)/delta,q=(max-start)/delta;enter=Math.Max(enter,Math.Min(p,q));leave=Math.Min(leave,Math.Max(p,q));if(enter>leave)return false;}}return true;}
 static bool Segment(LotPoint a,LotPoint b,Nav n){if(n.solids.Any(r=>Hits(a,b,r)))return false;int x=(int)Math.Floor(a.x*2),z=(int)Math.Floor(a.z*2),lastX=(int)Math.Floor(b.x*2),lastZ=(int)Math.Floor(b.z*2);int sx=Math.Sign(lastX-x),sz=Math.Sign(lastZ-z);float dx=b.x-a.x,dz=b.z-a.z;double ix=sx==0?double.PositiveInfinity:.5/Math.Abs(dx),iz=sz==0?double.PositiveInfinity:.5/Math.Abs(dz);double cx=sx==0?double.PositiveInfinity:((x+(sx>0?1:0))*.5-a.x)/dx,cz=sz==0?double.PositiveInfinity:((z+(sz>0?1:0))*.5-a.z)/dz;int count=Math.Abs(lastX-x)+Math.Abs(lastZ-z)+3;for(int i=0;i<count;i++){if(!n.points.ContainsKey(Key(x,z)))return false;if(x==lastX&&z==lastZ)return true;if(Math.Abs(cx-cz)<.000001){if(!n.points.ContainsKey(Key(x+sx,z))||!n.points.ContainsKey(Key(x,z+sz)))return false;x+=sx;z+=sz;cx+=ix;cz+=iz;}else if(cx<cz){x+=sx;cx+=ix;}else{z+=sz;cz+=iz;}}return false;} public bool MovementSegmentClear(LotPoint a,LotPoint b,bool constructed=true,int index=-1){if(!Finite(a.x)||!Finite(a.z)||!Finite(b.x)||!Finite(b.z))return false;return Segment(a,b,Graph(constructed,index<0?State.currentHotel:index));}public bool CanWalk(float x,float z){return MovementSegmentClear(new LotPoint(x,z),new LotPoint(x,z),false);}
 public List<LotPoint> Route(LotPoint a,LotPoint b,bool constructed=true,int index=-1){var result=new List<LotPoint>();if(!Finite(a.x)||!Finite(a.z)||!Finite(b.x)||!Finite(b.z))return result;var n=Graph(constructed,index<0?State.currentHotel:index);if(n.points.Count==0)return result;var start=n.points.OrderBy(p=>p.Value.Distance(a)).First();var goal=n.points.OrderBy(p=>p.Value.Distance(b)).First();if(start.Value.Distance(a)>1.5||goal.Value.Distance(b)>.8)return result;var came=new Dictionary<long,long>();var distance=new Dictionary<long,float>{{start.Key,0}};var open=new HashSet<long>{start.Key};while(open.Count>0){long key=open.OrderBy(k=>distance[k]+n.points[k].Distance(goal.Value)).First();open.Remove(key);if(key==goal.Key){while(key!=start.Key){result.Add(n.points[key]);key=came[key];}result.Add(start.Value);result.Reverse();var simple=new List<LotPoint>{result[0]};int at=0;while(at<result.Count-1){int next=result.Count-1;while(next>at+1&&!Segment(result[at],result[next],n))next--;simple.Add(result[next]);at=next;}return simple;}foreach(long next in n.edges[key]){float d=distance[key]+n.points[key].Distance(n.points[next]);if(!distance.TryGetValue(next,out float old)||d<old){distance[next]=d;came[next]=key;open.Add(next);}}}return result;}
 public List<LotPoint> ActivityRoute(LotPoint a,LotPoint b){var p=Route(a,b);return p.Count==0?Route(a,b,false):p;}
 List<LotPoint> Approaches(ObjectState o,int index){var b=Rect(o);var h=Hotel(index);var room=h.rooms.Find(r=>r.id==o.room);bool indoors=room!=null&&room.kind!="terrace";var arr=Map(index)["arrival"];var origin=new LotPoint((float)arr[0],(float)arr[1]);var result=new List<LotPoint>();foreach(var p in new[]{new LotPoint(b.x-.25f,b.z+b.d/2),new LotPoint(b.x+b.w+.25f,b.z+b.d/2),new LotPoint(b.x+b.w/2,b.z-.25f),new LotPoint(b.x+b.w/2,b.z+b.d+.25f)}){if(indoors&&!Rect(room).Has(p.x,p.z))continue;var route=Route(origin,p,indoors,index);if(route.Count==0)continue;var end=route[route.Count-1];if(end.Distance(p)>=.45||indoors&&!Rect(room).Has(end.x,end.z))continue;if(!result.Any(v=>v.Distance(end)<.01))result.Add(end);}return result;}
 public IReadOnlyList<VenueSnapshot> Venues(int index=-1){if(index<0)index=State.currentHotel;if(venueCache.TryGetValue(index,out var cached))return cached;var result=new List<VenueSnapshot>();var staffed=new HashSet<string>();foreach(var o in Hotel(index).objects){var item=Catalog.Find(o.itemId);if(new[]{"decoration","fence","gate"}.Contains(item.role))continue;var points=Approaches(o,index);var venue=new VenueSnapshot{id=o.id,item=o.itemId,name=item.name,room=o.room,x=o.x,z=o.z,role=item.role,service=item.service,tags=item.tags,capacity=Math.Max(1,item.capacity)};if((item.role=="reception"||item.role=="bar")&&points.Count>1){var b=Rect(o);float bx=(float)Math.Sin(o.rotation*Math.PI/2),bz=-(float)Math.Cos(o.rotation*Math.PI/2);var candidates=points.Where(p=>!staffed.Contains(SlotKey(p))).OrderByDescending(p=>{float dx=p.x-b.x-b.w/2,dz=p.z-b.z-b.d/2;return (dx*bx+dz*bz)/(float)Math.Sqrt(dx*dx+dz*dz);}).ToArray();if(candidates.Length>0){var p=candidates[0];venue.staffSlot=new VenueSlot{x=p.x,z=p.z,key=SlotKey(p)};staffed.Add(venue.staffSlot.key);points.Remove(p);}}foreach(var p in points)venue.slots.Add(new VenueSlot{x=p.x,z=p.z,key=SlotKey(p),action=o.itemId=="litter"?"dig":o.itemId=="box"?"peek":o.itemId=="scratch"?"scratch":item.role=="bar"?"eat":item.role=="play"?"play":"loaf"});if(item.role=="bar"&&venue.staffSlot==null)venue.slots.Clear();result.Add(venue);}foreach(var v in result){v.slots=v.slots.Where(s=>!staffed.Contains(s.key)).Take(v.capacity).ToList();v.capacity=v.slots.Count;v.open=v.capacity>0;v.status=v.open?"Open":"Needs access";}bool reception=result.Any(v=>v.role=="reception"&&v.open);foreach(var v in result){if(v.role=="bed"&&!reception){v.open=false;v.status="Needs reception";}if(v.role=="bar"&&v.open&&!result.Any(s=>s.role=="seat"&&s.open&&s.item!="cafe_table"&&s.room==v.room&&(v.room!=""||new LotPoint(v.x,v.z).Distance(new LotPoint(s.x,s.z))<=6)))v.status="Add seating";}venueCache[index]=result;return result;}
 static string SlotKey(LotPoint p){return "cell:"+p.x.ToString("F2",System.Globalization.CultureInfo.InvariantCulture)+","+p.z.ToString("F2",System.Globalization.CultureInfo.InvariantCulture);}
 readonly Dictionary<string,RoomStatusInfo> statusCache=new Dictionary<string,RoomStatusInfo>(); public RoomStatusInfo RoomStatus(string id,int index=-1){int h=index<0?State.currentHotel:index;string key=h+":"+id;if(statusCache.TryGetValue(key,out var cached))return cached;var result=ComputeRoomStatus(id,h);statusCache[key]=result;return result;} RoomStatusInfo ComputeRoomStatus(string id,int index=-1){if(index<0)index=State.currentHotel;var r=Hotel(index).rooms.Find(v=>v.id==id);if(r==null)return new RoomStatusInfo{status="Missing room",message="This room was removed."};var venues=Venues(index);if(r.kind=="shared"||r.kind=="terrace"){bool open=venues.Any(v=>v.room==id&&v.open);return new RoomStatusInfo{ready=open,status=open?"Open":"Add activities",message=open?"Cats can spend time here.":"Place a reachable counter, seat or activity."};}var beds=Hotel(index).objects.Where(o=>o.room==id&&Catalog.Find(o.itemId).role=="bed").ToArray();string status=beds.Length==0?"Needs a bed":!venues.Any(v=>v.role=="reception"&&v.open)?"Needs reception":!beds.Any(b=>Approaches(b,index).Count>0)?"Needs a path":"Ready for guests";double bonus=0;var items=Hotel(index).objects.Where(o=>o.room==id).Select(o=>o.itemId).ToHashSet();foreach(var combo in Content.Raw["combos"]??new JArray())if(status=="Ready for guests"&&(combo["items"].All(i=>items.Contains((string)i))))bonus+=(double)combo["bonus"];return new RoomStatusInfo{ready=status=="Ready for guests",status=status,message=status=="Needs a bed"?"Add a reachable bed to welcome guests.":status=="Needs reception"?"Connect a reception counter to the entrance.":status=="Needs a path"?"Connect the door and bed to reception.":"A bed and a welcoming route are ready."+(bonus>0?" Furnishing combinations add "+(int)bonus+"/min.":""),bonus=bonus};}
 public bool IsRoomReady(RoomState r){return r!=null&&RoomStatus(r.id).ready;}public int GuestCapacity(int index=-1){if(index<0)index=State.currentHotel;return Hotel(index).rooms.Where(r=>(r.kind=="regular"||r.kind=="suite")&&RoomStatus(r.id,index).ready).Sum(r=>r.kind=="suite"?4:2);}
 public double Rate(int index=-1){double total=0;for(int i=0;i<State.hotels.Count;i++){if(index>=0&&index!=i||!Hotel(i).owned)continue;var h=Hotel(i);var families=new HashSet<int>();foreach(var r in h.rooms)if((r.kind=="regular"||r.kind=="suite")&&RoomStatus(r.id,i).ready){total+=(r.kind=="suite"?28:12)+RoomStatus(r.id,i).bonus;families.Add(0);}foreach(var v in Venues(i))if(v.open&&v.service>0)families.Add(v.service);foreach(int f in families)total+=Math.Max(1,h.upgrades[f])*10;total+=h.staff.Sum()*2;}return total;}
 public CommandResult SetViewSettings(bool exterior,bool evening){return SetSettings(State.settings.textScale,State.settings.motion,State.settings.music,State.settings.sound,exterior,evening);}
}
}



