using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Newtonsoft.Json.Linq;
namespace Purrington.Domain {
[Serializable] public sealed class FloorState {public int level;public Dictionary<string,double> cells=new Dictionary<string,double>();public Dictionary<string,EdgeState> edges=new Dictionary<string,EdgeState>();}
// room is the owning room id for walls regenerated from room rectangles, or "" for walls, doors and windows the player placed.
[Serializable] public sealed class EdgeState {public string kind="wall",room="";public double paid;}
// Grid edges between hotel cells. "v:x,z" lies on grid line x between cells (x-1,z) and (x,z); "h:x,z" lies on line z between (x,z-1) and (x,z).
public static class ShellGrid {
 public const double CellPrice=20,WallPrice=5,DoorPrice=20,WindowPrice=15,OpenPrice=10;
 public static readonly string[] Kinds={"wall","door","window","open"};
 public static string Cell(int x,int z){return x.ToString(CultureInfo.InvariantCulture)+","+z.ToString(CultureInfo.InvariantCulture);}
 public static bool TryCell(string key,out int x,out int z){x=z=0;var p=key?.Split(',');return p!=null&&p.Length==2&&int.TryParse(p[0],NumberStyles.Integer,CultureInfo.InvariantCulture,out x)&&int.TryParse(p[1],NumberStyles.Integer,CultureInfo.InvariantCulture,out z)&&Cell(x,z)==key;}
 public static string Edge(char axis,int x,int z){return axis+":"+Cell(x,z);}
 public static bool TryEdge(string key,out char axis,out int x,out int z){axis='?';x=z=0;if(key==null||key.Length<5||key[1]!=':'||(key[0]!='v'&&key[0]!='h'))return false;axis=key[0];return TryCell(key.Substring(2),out x,out z);}
 public static void Sides(string edge,out string a,out string b){TryEdge(edge,out char axis,out int x,out int z);a=axis=='v'?Cell(x-1,z):Cell(x,z-1);b=Cell(x,z);}
 public static IEnumerable<string> CellEdges(int x,int z){yield return Edge('v',x,z);yield return Edge('v',x+1,z);yield return Edge('h',x,z);yield return Edge('h',x,z+1);}
 public static IEnumerable<string> Cells(int x,int z,int w,int d){for(int i=0;i<w;i++)for(int j=0;j<d;j++)yield return Cell(x+i,z+j);}
 public static IEnumerable<string> Boundary(int x,int z,int w,int d){for(int i=0;i<w;i++){yield return Edge('h',x+i,z);yield return Edge('h',x+i,z+d);}for(int j=0;j<d;j++){yield return Edge('v',x,z+j);yield return Edge('v',x+w,z+j);}}
 public static IEnumerable<string> Inside(int x,int z,int w,int d){for(int i=1;i<w;i++)for(int j=0;j<d;j++)yield return Edge('v',x+i,z+j);for(int i=0;i<w;i++)for(int j=1;j<d;j++)yield return Edge('h',x+i,z+j);}
 // Doors are centered on a side: one edge on odd lengths, a double door on even lengths, so HotelModel.DoorPosition stays exact. Sides: 0 +x, 1 +z, 2 -x, 3 -z.
 public static IEnumerable<string> DoorEdges(int x,int z,int w,int d,int side){bool ew=side==0||side==2;int length=ew?d:w;for(int i=(length-1)/2;i<=length/2;i++)yield return side==0?Edge('v',x+w,z+i):side==1?Edge('h',x+i,z+d):side==2?Edge('v',x,z+i):Edge('h',x+i,z);}
 public static bool Indoor(FloorState f,string cell){return f!=null&&f.cells.ContainsKey(cell);}
 public static bool Exterior(FloorState f,string edge){Sides(edge,out var a,out var b);return Indoor(f,a)!=Indoor(f,b);}
 // wall, door, window, open (archway), or null for open floor and bare land.
 public static string WallAt(FloorState f,string edge){Sides(edge,out var a,out var b);bool ia=Indoor(f,a),ib=Indoor(f,b);if(!ia&&!ib)return null;if(f.edges.TryGetValue(edge,out var e))return e.kind;return ia!=ib?"wall":null;}
 public static double Price(string kind){return kind=="wall"?WallPrice:kind=="door"?DoorPrice:kind=="window"?WindowPrice:kind=="open"?OpenPrice:0;}
 public static IEnumerable<string> Edges(FloorState f){var seen=new HashSet<string>();foreach(var c in f.cells.Keys){TryCell(c,out int x,out int z);foreach(var e in CellEdges(x,z))if(seen.Add(e))yield return e;}}
 public static void EdgeCenter(string edge,out float x,out float z){TryEdge(edge,out char axis,out int ex,out int ez);x=axis=='v'?ex:ex+.5f;z=axis=='v'?ez+.5f:ez;}
}
public static class ShellMigration {
 // v2 rooms were free-standing boxes; v3 keeps each as a shell island with room-owned walls, so migrated hotels look and route the same.
 public static bool Upgrade(HotelState s){if(s==null||s.hotels==null)return false;if(s.version==3)return true;if(s.version!=2)return false;foreach(var h in s.hotels){if(h==null)return false;if(h.floors==null)h.floors=new List<FloorState>();foreach(var r in h.rooms??new List<RoomState>())if(r!=null)r.floor=0;foreach(var o in h.objects??new List<ObjectState>())if(o!=null)o.floor=0;var ground=HotelModel.Floor(h,0,true);foreach(var r in h.rooms??new List<RoomState>()){if(r==null||!HotelModel.IndoorKind(r.kind)||r.width<1||r.depth<1||r.width>80||r.depth>80||r.x<-256||r.x>256||r.z<-256||r.z>256)continue;HotelModel.RoomSize(r,out float w,out float d);foreach(var c in ShellGrid.Cells(r.x,r.z,(int)w,(int)d)){ground.cells[c]=0;if(h.paths!=null&&h.paths.TryGetValue(c,out var path)){s.coins+=path.paid;h.paths.Remove(c);}}}if(h.rooms!=null)HotelModel.SyncRoomWalls(h);}s.version=3;return true;}
}
public sealed partial class HotelModel {
 public static FloorState Floor(HotelData h,int level,bool create=false){var f=h.floors.Find(v=>v!=null&&v.level==level);if(f==null&&create){f=new FloorState{level=level};h.floors.Add(f);h.floors.Sort((a,b)=>a.level.CompareTo(b.level));}return f;}
 public static bool IndoorKind(string kind){return kind=="regular"||kind=="suite"||kind=="shared";}
 static void RoomCells(RoomState r,out int x,out int z,out int w,out int d){RoomSize(r,out float fw,out float fd);x=r.x;z=r.z;w=(int)fw;d=(int)fd;}
 public static bool Interior(HotelData h,RoomState r){var f=Floor(h,r.floor);if(f==null)return false;RoomCells(r,out int x,out int z,out int w,out int d);return ShellGrid.Cells(x,z,w,d).All(f.cells.ContainsKey);}
 static IEnumerable<int> DoorSides(RoomState r){return r.kind=="shared"?new[]{0,1,2,3}:new[]{r.door>=0?r.door:r.rotation};}
 static double Fitting(RoomState r){return Math.Round(Shell(r)*.45,MidpointRounding.AwayFromZero);}
 // Room walls are regenerated from room rectangles after every command; player-placed edges (room=="") are never touched. Doors go first so a neighbour's wall never swallows a room's only door.
 internal static void SyncRoomWalls(HotelData h){foreach(var f in h.floors){foreach(var k in f.edges.Where(e=>e.Value.room!="").Select(e=>e.Key).ToList())f.edges.Remove(k);var rooms=h.rooms.Where(v=>v.floor==f.level&&IndoorKind(v.kind)&&Interior(h,v)).ToList();foreach(var r in rooms){RoomCells(r,out int x,out int z,out int w,out int d);foreach(var e in DoorSides(r).SelectMany(s=>ShellGrid.DoorEdges(x,z,w,d,s)))if(!f.edges.ContainsKey(e))f.edges[e]=new EdgeState{kind="door",room=r.id};}foreach(var r in rooms){RoomCells(r,out int x,out int z,out int w,out int d);foreach(var e in ShellGrid.Boundary(x,z,w,d))if(!f.edges.ContainsKey(e)&&!ShellGrid.Exterior(f,e))f.edges[e]=new EdgeState{kind="wall",room=r.id};}}}
 CommandResult ApplyShell(string action,JObject p,HotelData h){int level=(int?)p["floor"]??0;if(level!=0)return CommandResult.Fail("Upper floors open with a stairwell.");if(action=="set_edge")return SetEdges(h,level,p);if(!(p["cells"] is JArray raw)||raw.Count==0||raw.Count>4096)return CommandResult.Fail("Drag across the floor you want.");var cells=new List<(int x,int z)>();foreach(var cell in raw){if(!(cell is JArray pair)||pair.Count!=2||!Whole(pair[0])||!Whole(pair[1]))return CommandResult.Fail("Paint whole floor cells.");cells.Add(((int)pair[0],(int)pair[1]));}return action=="paint_floor"?PaintCells(h,level,cells,(bool?)p["buy"]??false):EraseCells(h,level,cells);}
 CommandResult PaintCells(HotelData h,int level,IEnumerable<(int x,int z)> cells,bool buy){var f=Floor(h,level,true);double cost=0;int added=0;var bought=new List<string>();foreach(var (x,z) in cells){string key=ShellGrid.Cell(x,z);if(f.cells.ContainsKey(key))continue;if(!Owned(x+.5f,z+.5f,State.currentHotel)){var plot=buy?Map()["plots"].FirstOrDefault(t=>!h.plots.Contains((string)t["id"])&&Rect(t["rect"]).Has(x+.5f,z+.5f)):null;if(plot==null)return CommandResult.Fail("Grow the hotel on land you own.");h.plots.Add((string)plot["id"]);bought.Add((string)plot["name"]);cost+=Price((double)plot["cost"]);}if(h.paths.TryGetValue(key,out var path)){cost-=path.paid;h.paths.Remove(key);}double price=Price(ShellGrid.CellPrice);f.cells[key]=price;cost+=price;added++;}if(added==0)return CommandResult.Fail("That floor is already part of the hotel.");foreach(var e in f.edges.Where(v=>v.Value.kind=="open"&&!ShellGrid.Exterior(f,v.Key)).Select(v=>v.Key).ToList()){cost-=f.edges[e].paid;f.edges.Remove(e);}return CommandResult.Ok((bought.Count>0?"Bought "+string.Join(" and ",bought)+" · ":"")+"The hotel grows by "+added+(added==1?" tile":" tiles"),cost);}
 CommandResult EraseCells(HotelData h,int level,IEnumerable<(int x,int z)> cells){var f=Floor(h,level);if(f==null)return CommandResult.Fail("There is no hotel floor there.");double cost=0;int removed=0;foreach(var (x,z) in cells){string key=ShellGrid.Cell(x,z);if(!f.cells.TryGetValue(key,out double paid))continue;if(h.rooms.Any(r=>r.floor==level&&Rect(r).Has(x+.5f,z+.5f)))return CommandResult.Fail("Remove the room here first.");cost-=paid;f.cells.Remove(key);removed++;}if(removed==0)return CommandResult.Fail("There is no hotel floor there.");foreach(var e in f.edges.Keys.ToList()){ShellGrid.Sides(e,out var a,out var b);if(!f.cells.ContainsKey(a)&&!f.cells.ContainsKey(b)){cost-=f.edges[e].paid;f.edges.Remove(e);}}return CommandResult.Ok("Floor removed",cost);}
 CommandResult SetEdges(HotelData h,int level,JObject p){string kind=(string)p["kind"]??"";if(kind!="none"&&!ShellGrid.Kinds.Contains(kind))return CommandResult.Fail("Choose wall, door, window or archway.");if(!(p["edges"] is JArray edges)||edges.Count==0||edges.Count>512)return CommandResult.Fail("Choose a wall edge.");var f=Floor(h,level);if(f==null)return CommandResult.Fail("Build hotel floor first.");double cost=0;foreach(var raw in edges){string e=raw.Type==JTokenType.String?(string)raw:null;if(!ShellGrid.TryEdge(e,out _,out _,out _))return CommandResult.Fail("Choose a wall edge.");ShellGrid.Sides(e,out var a,out var b);if(!f.cells.ContainsKey(a)&&!f.cells.ContainsKey(b))return CommandResult.Fail("Walls belong on the hotel floor.");f.edges.TryGetValue(e,out var prior);if(kind=="none"&&prior==null)return CommandResult.Fail("There's nothing to remove here.");if(prior!=null&&prior.room!=""&&(kind=="none"||kind=="open"))return CommandResult.Fail("This wall encloses a room.");if(kind=="open"&&!ShellGrid.Exterior(f,e))return CommandResult.Fail("Archways go on outside walls; inside, just leave the floor open.");cost-=prior?.paid??0;if(kind=="none"){f.edges.Remove(e);continue;}double price=Price(ShellGrid.Price(kind));f.edges[e]=new EdgeState{kind=kind,paid=price};cost+=price;}return CommandResult.Ok(kind=="none"?"Wall removed":kind=="open"?"Archway added":kind=="door"?"Door added":kind=="window"?"Window added":"Wall added",cost);}
 static bool IndoorAt(HotelData h,int level,LotRect b){return ShellGrid.Indoor(Floor(h,level),ShellGrid.Cell((int)Math.Floor(b.x+b.w/2),(int)Math.Floor(b.z+b.d/2)));}
 static bool Crosses(LotRect b,string edge){ShellGrid.TryEdge(edge,out char axis,out int x,out int z);return axis=='v'?x>b.x&&x<b.x+b.w&&z+1>b.z&&z<b.z+b.d:z>b.z&&z<b.z+b.d&&x+1>b.x&&x<b.x+b.w;}
 internal CommandResult ValidateShell(int index){var h=Hotel(index);var levels=new HashSet<int>();foreach(var f in h.floors){if(f==null||f.cells==null||f.edges==null||!levels.Add(f.level)||f.level!=0)return CommandResult.Fail("Keep hotel floors tidy.");foreach(var c in f.cells){if(!ShellGrid.TryCell(c.Key,out int x,out int z)||Math.Abs(x)>256||Math.Abs(z)>256||!Finite(c.Value)||c.Value<0||c.Value>ShellGrid.CellPrice)return CommandResult.Fail("Keep hotel floors tidy.");if(!Owned(x+.5f,z+.5f,index))return CommandResult.Fail("Grow the hotel on land you own.");foreach(var s in Map(index)["scenery"]??new JArray())if((bool?)s["protected"]==true&&new LotRect((float)s["x"],(float)s["y"],(float?)s["size"]??2,(float?)s["size"]??2).Intersects(new LotRect(x,z,1,1)))return CommandResult.Fail("Keep this scenic landmark clear.");}foreach(var e in f.edges){if(!ShellGrid.TryEdge(e.Key,out _,out _,out _)||e.Value==null||!ShellGrid.Kinds.Contains(e.Value.kind)||e.Value.room==null||!Finite(e.Value.paid)||e.Value.paid<0||e.Value.paid>ShellGrid.Price(e.Value.kind))return CommandResult.Fail("Keep hotel walls tidy.");ShellGrid.Sides(e.Key,out var a,out var b);if(!f.cells.ContainsKey(a)&&!f.cells.ContainsKey(b))return CommandResult.Fail("Walls belong on the hotel floor.");if(e.Value.kind=="open"&&!ShellGrid.Exterior(f,e.Key))return CommandResult.Fail("Archways go on outside walls; inside, just leave the floor open.");}}
  foreach(var r in h.rooms){var f=Floor(h,r.floor);RoomCells(r,out int x,out int z,out int w,out int d);int inside=f==null?0:ShellGrid.Cells(x,z,w,d).Count(f.cells.ContainsKey);if(inside==0){if(r.floor!=0)return CommandResult.Fail("Upper-floor rooms need floor under them.");continue;}if(inside!=w*d||!IndoorKind(r.kind))return CommandResult.Fail("Draw rooms fully inside the hotel or fully outside it.");if(ShellGrid.Inside(x,z,w,d).Any(f.edges.ContainsKey))return CommandResult.Fail("Walls can't cut through a room.");var walls=ShellGrid.Boundary(x,z,w,d).Select(e=>ShellGrid.WallAt(f,e)).ToList();if(walls.Any(k=>k==null||k=="open"))return CommandResult.Fail("Rooms need walls all the way around.");if(!walls.Contains("door"))return CommandResult.Fail("Every room needs a door.");}
  foreach(var o in h.objects){var f=Floor(h,o.floor);var b=Rect(o);int inside=0,total=0;for(int x=(int)Math.Floor(b.x);x<Math.Ceiling(b.x+b.w);x++)for(int z=(int)Math.Floor(b.z);z<Math.Ceiling(b.z+b.d);z++){total++;if(ShellGrid.Indoor(f,ShellGrid.Cell(x,z)))inside++;}if(inside>0&&inside<total)return CommandResult.Fail("Keep furniture inside the hotel or outside its walls.");if(o.floor!=0&&inside==0)return CommandResult.Fail("Upper-floor furniture needs floor under it.");if(inside>0&&f.edges.Keys.Any(e=>Crosses(b,e)))return CommandResult.Fail("Furniture can't sit across a wall.");}
  return CommandResult.Ok("Valid");}
}
}
