using System;using System.Collections.Generic;using System.Linq;using Newtonsoft.Json.Linq;
namespace Purrington.Domain {
public sealed partial class HotelModel {
 sealed class Actor {public ActorSnapshot view=new ActorSnapshot();public string phase="idle",slot="",slotAction,activityVenue,sourceRoom,cleanRoom;public bool checkedIn;public List<LotPoint> route=new List<LotPoint>();public List<string> recent=new List<string>();public int waypoint,completed;public float remaining,blocked,stay;public string[] tags=Array.Empty<string>();public LotPoint Position=>new LotPoint(view.x,view.z);}
 readonly List<Actor> actors=new List<Actor>();readonly Dictionary<string,int> reservations=new Dictionary<string,int>();long activitySerial;int lifeRevision=-1,rosterCursor,turn;float socialClock,nextMoment=17,momentRemaining,rosterClock;int momentSerial;JArray momentLines;readonly List<string> recentDialogue=new List<string>();Actor momentA,momentB;readonly Dictionary<int,float> socialCooldown=new Dictionary<int,float>();readonly Dictionary<string,float> pairCooldown=new Dictionary<string,float>();
 public IReadOnlyList<ActorSnapshot> Actors=>actors.Select(a=>{a.view.phase=a.phase;a.view.slot=a.slot;a.view.sourceRoom=a.sourceRoom;a.view.checkedIn=a.checkedIn;a.view.remaining=a.remaining;a.view.completed=a.completed;a.view.drink=a.view.action=="drink";return a.view;}).ToArray(); public IReadOnlyDictionary<string,int> Reservations=>new Dictionary<string,int>(reservations);public int SocialSerial=>momentSerial;public bool SocialActive=>momentRemaining>0;public void CancelSocial(){CancelMoment();}
 void ResetLife(){actors.Clear();reservations.Clear();lifeRevision=-1;rosterCursor=0;turn=0;socialClock=0;rosterClock=0;momentSerial=0;recentDialogue.Clear();nextMoment=17;momentRemaining=0;momentA=momentB=null;socialCooldown.Clear();pairCooldown.Clear();}
 void Activity(Actor a,string phase,string action,float duration){bool changed=a.phase!=phase||a.view.action!=action;a.phase=phase;a.view.action=action;a.remaining=duration;if(changed){a.view.activityToken=++activitySerial;a.view.activityElapsed=0;a.view.activityDuration=duration;}}
 void Release(Actor a){if(reservations.TryGetValue(a.slot,out int cat)&&cat==a.view.catId)reservations.Remove(a.slot);a.slot="";}
 bool Free(LotPoint p,Actor except=null,bool reserved=false,float spacing=.72f){return actors.All(a=>a==except||a.Position.Distance(p)>=spacing&&(!reserved||a.slot==""||a.route.Count==0||a.route[a.route.Count-1].Distance(p)>=spacing));}
 LotPoint Arrival(){var a=Map()["arrival"];return new LotPoint((float)a[0],(float)a[1]);}
 LotPoint? FreeArrival(Actor except=null){var origin=Arrival();for(int ring=0;ring<12;ring++)for(int k=0;k<Math.Max(1,ring*8);k++){float angle=(float)(Math.PI*2*k/Math.Max(1,ring*8));var candidate=new LotPoint(origin.x+(float)Math.Cos(angle)*ring*.8f,origin.z+(float)Math.Sin(angle)*ring*.8f);var path=ActivityRoute(origin,candidate);if(path.Count==0)continue;var p=path[path.Count-1];if(Free(p,except,false,1.94f)&&!Venues().Any(v=>v.staffSlot!=null&&new LotPoint(v.staffSlot.x,v.staffSlot.z).Distance(p)<.72))return p;}return null;}
 void Sync(){var venues=Venues();if(lifeRevision!=Revision){reservations.Clear();foreach(var a in actors){Release(a);if(!CanWalk(a.view.x,a.view.z)||!Free(a.Position,a)){var p=FreeArrival(a);if(p.HasValue){a.view.x=p.Value.x;a.view.z=p.Value.z;}}a.view.venueId="";a.route.Clear();Activity(a,"idle","rest",.12f*(a.view.catId%4));}lifeRevision=Revision;CancelMoment();}
 int capacity=GuestCapacity();foreach(var a in actors.Where(a=>a.view.catId<1000).ToArray()){if(!State.cats[a.view.catId].known||capacity--<=0){Release(a);actors.Remove(a);}}
 capacity=GuestCapacity();while(actors.Count(a=>a.view.catId<1000)<Math.Min(capacity,State.cats.Count(c=>c.known))){CatState c=null;for(int i=0;i<State.cats.Count;i++){var candidate=State.cats[(rosterCursor+i)%State.cats.Count];if(candidate.known&&!actors.Any(a=>a.view.catId==candidate.id)){c=candidate;break;}}if(c==null)break;var p=FreeArrival();if(!p.HasValue)break;var actor=new Actor{view=new ActorSnapshot{id="cat:"+c.id,catId=c.id,name=c.name,role="guest",x=p.Value.x,z=p.Value.z},remaining=c.id%4*.45f};actors.Add(actor);rosterCursor=(c.id+1)%State.cats.Count;}
 var staffKeys=new HashSet<string>();var staffPositions=new List<LotPoint>();var staffNumbers=new Dictionary<string,int>();foreach(var v in venues.Where(v=>v.staffSlot!=null&&v.open)){var station=new LotPoint(v.staffSlot.x,v.staffSlot.z);if(staffPositions.Any(p=>p.Distance(station)<.72))continue;staffPositions.Add(station);int staffNumber=staffNumbers.TryGetValue(v.role,out int count)?count:0;staffNumbers[v.role]=staffNumber+1;string[] names=v.role=="bar"?new[]{"Saffron","Honey","Nutmeg","Cinnamon","Ginger","Cocoa"}:new[]{"Pippin","Poppy","Cedar","Wren","Robin","Willow"};string staffName=names[staffNumber%names.Length]+(staffNumber>=names.Length?" "+(staffNumber/names.Length+1):"");string id="staff:"+v.id;staffKeys.Add(id);var a=actors.Find(n=>n.view.id==id);if(a==null){a=new Actor{view=new ActorSnapshot{id=id,catId=2000+(int)(StableHash(v.id)%1000000),name=staffName,role=v.role=="bar"?"barista":"concierge"}};actors.Add(a);}a.view.x=v.staffSlot.x;a.view.z=v.staffSlot.z;foreach(var guest in actors.Where(g=>g!=a&&g.Position.Distance(a.Position)<.72).ToArray()){var position=FreeArrival(guest);if(position.HasValue){Release(guest);guest.view.x=position.Value.x;guest.view.z=position.Value.z;guest.route.Clear();Activity(guest,"idle","rest",.1f);}}a.view.venueId=v.id;a.slot=v.staffSlot.key;reservations[a.slot]=a.view.catId;Activity(a,"staff",actors.Any(g=>g.view.catId<1000&&g.view.venueId==v.id&&g.phase=="serve")?"serve":v.role=="reception"?"greet":"work",0);}
 foreach(var a in actors.Where(a=>a.view.catId>=1000&&a.view.role!="housekeeper"&&!staffKeys.Contains(a.view.id)).ToArray()){Release(a);actors.Remove(a);}if(Hotel().maid&&!actors.Any(a=>a.view.role=="housekeeper")){var p=FreeArrival();if(p.HasValue)actors.Add(new Actor{view=new ActorSnapshot{id="staff:daisy",catId=1000,name="Buttons",role="housekeeper",x=p.Value.x,z=p.Value.z}});}}
 public void Tick(float seconds){if(RequiresSaveRecovery||!Finite(seconds)||seconds<=0)return;State.elapsed+=seconds;State.coins+=Rate()*seconds/60;for(int i=0;i<State.hotels.Count;i++){var h=Hotel(i);if(!h.owned)continue;h.dirtClock+=seconds;if(h.dirtClock>=120){h.dirtClock%=120;var rooms=h.rooms.Where(r=>(r.kind=="regular"||r.kind=="suite")&&RoomStatus(r.id,i).ready).ToArray();if(rooms.Length>0){int cursor=h.dirtCursor%rooms.Length;h.dirty[rooms[cursor].id]=true;h.dirtCursor=cursor+1;}}}Sync();float left=seconds;while(left>.00001f){float dt=Math.Min(.2f,left);rosterClock+=dt;foreach(var a in actors.ToArray()){a.view.activityElapsed+=dt;a.stay+=dt;if(a.view.role=="concierge"||a.view.role=="barista")continue;if(momentRemaining>0&&(a==momentA||a==momentB))continue;AdvanceActor(a,dt);}AdvanceMoments(dt);left-=dt;}Changed?.Invoke();}
 void AdvanceActor(Actor a,float dt){if(a.phase.StartsWith("walk")){Walk(a,dt);return;}a.remaining-=dt;if(a.remaining>0)return;if(a.view.role=="housekeeper"){if(a.phase=="clean"){Hotel().dirty[a.cleanRoom]=false;Hotel().cleaned++;Release(a);a.cleanRoom=null;}ChooseCleaning(a);return;}if(a.phase=="idle"){Choose(a);return;}if(a.phase=="order"){Activity(a,"serve","wait",2.8f);return;}if(a.phase=="serve"){if(!FindSeat(a))Activity(a,"activity","drink",7.5f);return;}if(a.phase=="activity"||a.phase=="sit"){if(a.view.action=="greet")a.checkedIn=true;else{Hotel().visits++;var c=State.cats[a.view.catId];if(a.tags.Contains(c.preference)){Hotel().happy++;c.bond=Math.Min(100,c.bond+1);var next=State.cats.Find(n=>!n.known&&n.id<12&&n.preference==c.preference);if(next!=null)next.known=true;}a.completed++;}a.recent.Add(a.activityVenue??a.view.venueId);if(a.recent.Count>3)a.recent.RemoveAt(0);Release(a);a.view.venueId="";if(a.checkedIn&&rosterClock>=90&&State.cats.Any(c=>c.known&&!actors.Any(v=>v.view.catId==c.id))){var path=ActivityRoute(a.Position,Arrival());if(path.Count>0){a.route=path;a.waypoint=0;rosterClock=0;Activity(a,"walk_depart","departure",0);return;}}Activity(a,"idle","rest",a.view.action=="greet"?.5f:2+a.view.catId%3*.5f);}}
 static uint StableHash(string s){uint hash=5381;foreach(char c in s)hash=((hash<<5)+hash)+c;return hash;}
 void Choose(Actor a){var cat=State.cats[a.view.catId];var choices=Venues().Where(v=>v.open&&(a.checkedIn?v.role!="reception":v.role=="reception")).OrderByDescending(v=>1+(v.tags.Contains(cat.preference)?5:0)-(a.recent.Contains(v.id)?6:0)+(v.role=="bar"?1.2:v.role=="reception"?-.8:0)+FriendScore(a,v)+((StableHash(v.id)+(uint)(a.view.catId*17+turn*7))%97)/97.0);foreach(var v in choices)foreach(var slot in v.slots){if(reservations.ContainsKey(slot.key))continue;var p=new LotPoint(slot.x,slot.z);if(!Free(p,a,true))continue;var path=ActivityRoute(a.Position,p);if(path.Count==0)continue;Reserve(a,v,slot,path,false);a.tags=v.tags;turn++;return;}if(a.checkedIn&&Wander(a))return;Activity(a,"idle","rest",1.2f+a.view.catId%3*.3f);}
 double FriendScore(Actor a,VenueSnapshot v){if(!new[]{"seat","bar","play","warm","sun"}.Contains(v.role))return 0;var friend=actors.Find(f=>f.view.catId==State.cats[a.view.catId].friend);if(friend==null)return 0;var place=Venues().FirstOrDefault(p=>p.id==friend.view.venueId);return place!=null&&place.room==v.room&&new LotPoint(v.x,v.z).Distance(friend.Position)<5?4:0;} bool Wander(Actor a){for(int n=0;n<8;n++){float angle=(float)((a.view.catId+turn+n)%8*Math.PI*.25);var p=new LotPoint(a.view.x+(float)Math.Cos(angle)*2.5f,a.view.z+(float)Math.Sin(angle)*2.5f);if(Hotel().rooms.Any(r=>Rect(r).Grow(.2f).Has(p.x,p.z)))continue;var route=Route(a.Position,p,false);if(route.Count<1||route[route.Count-1].Distance(a.Position)<.8)continue;a.route=route;a.waypoint=0;Activity(a,"walk_wander","walk",0);turn++;return true;}return false;}
 void Reserve(Actor a,VenueSnapshot v,VenueSlot s,List<LotPoint> path,bool seat){Release(a);reservations[s.key]=a.view.catId;a.slot=s.key;a.view.venueId=v.id;a.slotAction=s.action;a.route=path;a.waypoint=0;if(!seat){a.activityVenue=v.id;a.sourceRoom=v.room;}Activity(a,seat?"walk_seat":"walk","walk",0);}
 bool FindSeat(Actor a){foreach(var v in Venues().Where(v=>v.open&&v.role=="seat"&&v.item!="cafe_table"&&v.room==a.sourceRoom&&(v.room!=""||a.Position.Distance(new LotPoint(v.x,v.z))<=6)).OrderBy(v=>a.Position.Distance(new LotPoint(v.x,v.z))))foreach(var s in v.slots){if(reservations.ContainsKey(s.key)||!Free(new LotPoint(s.x,s.z),a,true))continue;var route=ActivityRoute(a.Position,new LotPoint(s.x,s.z));if(route.Count==0)continue;Reserve(a,v,s,route,true);return true;}return false;}
 bool StepClear(Actor a,LotPoint from,LotPoint to){if(!MovementSegmentClear(from,to,false))return false;foreach(var b in actors){if(a==b)continue;float dx=to.x-from.x,dz=to.z-from.z,den=dx*dx+dz*dz;float t=den==0?0:Math.Max(0,Math.Min(1,((b.view.x-from.x)*dx+(b.view.z-from.z)*dz)/den));if(new LotPoint(from.x+dx*t,from.z+dz*t).Distance(b.Position)<.7199)return false;}return true;}
 void Avoid(Actor a){if(a.route.Count==0)return;var target=a.route[a.route.Count-1];var nav=Graph(false,State.currentHotel);var blocked=new HashSet<long>(nav.points.Where(p=>!Free(p.Value,a,false,.72f)).Select(p=>p.Key));var route=Avoidance(a.Position,target,nav,blocked);if(route.Count>0){a.route=route;a.waypoint=0;return;}foreach(var waiting in actors.Where(w=>w!=a&&w.phase=="idle"&&w.slot==""&&w.Position.Distance(a.Position)<=1.5)){float away=(float)Math.Atan2(waiting.view.z-a.view.z,waiting.view.x-a.view.x);foreach(float angleOffset in new[]{0f,1.5708f,-1.5708f,.7854f,-.7854f}){var targetPoint=new LotPoint(waiting.view.x+(float)Math.Cos(away+angleOffset)*1.25f,waiting.view.z+(float)Math.Sin(away+angleOffset)*1.25f);if(!StepClear(waiting,waiting.Position,targetPoint))continue;waiting.route=new List<LotPoint>{targetPoint};waiting.waypoint=0;Activity(waiting,"walk_wander","walk",0);return;}}var next=a.route[Math.Min(a.waypoint,a.route.Count-1)];float angle=(float)Math.Atan2(next.z-a.view.z,next.x-a.view.x);foreach(float turnAngle in new[]{1.5708f,-1.5708f,2.3562f,-2.3562f,3.14159f}){var p=new LotPoint(a.view.x+(float)Math.Cos(angle+turnAngle)*.8f,a.view.z+(float)Math.Sin(angle+turnAngle)*.8f);if(!StepClear(a,a.Position,p))continue;a.route=a.route.Skip(a.waypoint).ToList();a.route.Insert(0,p);a.waypoint=0;return;}}
 List<LotPoint> Avoidance(LotPoint from,LotPoint to,Nav nav,HashSet<long> blocked){var empty=new List<LotPoint>();var start=nav.points.Where(p=>!blocked.Contains(p.Key)).OrderBy(p=>p.Value.Distance(from)).FirstOrDefault();long goal=Key(to);if(start.Value.Distance(from)>.8||blocked.Contains(goal)||!nav.points.ContainsKey(goal))return empty;var open=new Queue<long>();var came=new Dictionary<long,long>();open.Enqueue(start.Key);came[start.Key]=start.Key;while(open.Count>0){long k=open.Dequeue();if(k==goal){while(k!=start.Key){empty.Add(nav.points[k]);k=came[k];}empty.Add(start.Value);empty.Reverse();return StepClearForObstacles(from,empty[0])?empty:new List<LotPoint>();}foreach(long next in nav.edges[k])if(!blocked.Contains(next)&&!came.ContainsKey(next)){came[next]=k;open.Enqueue(next);}}return empty;}
 bool StepClearForObstacles(LotPoint a,LotPoint b){return MovementSegmentClear(a,b,false);}
 void Walk(Actor a,float dt){float distance=dt*1.35f;if(a.waypoint==0&&a.route.Count>1&&StepClear(a,a.Position,a.route[1]))a.waypoint=1;while(distance>0&&a.waypoint<a.route.Count){var p=a.route[a.waypoint];float gap=a.Position.Distance(p);if(gap<.001){a.waypoint++;continue;}float move=Math.Min(gap,distance),dx=(p.x-a.view.x)/gap,dz=(p.z-a.view.z)/gap;var candidate=new LotPoint(a.view.x+dx*move,a.view.z+dz*move);if(!StepClear(a,a.Position,candidate)){a.blocked+=dt;if(a.blocked>=.35f+a.view.catId%3*.08f){Avoid(a);a.blocked=0;}return;}a.view.x=candidate.x;a.view.z=candidate.z;a.view.facing=(float)Math.Atan2(dx,dz);distance-=move;a.blocked=0;if(move>=gap-.001)a.waypoint++;}if(a.waypoint<a.route.Count)return;if(a.phase=="walk_depart"){Release(a);actors.Remove(a);Sync();return;}if(a.phase=="walk_wander"){Activity(a,"idle","rest",2);return;}if(a.phase=="walk_clean"){Activity(a,"clean","clean",5);return;}if(a.phase=="walk_seat"){Activity(a,"sit","drink",8);return;}var v=Venues().FirstOrDefault(n=>n.id==a.view.venueId);if(v==null){Release(a);Activity(a,"idle","rest",1);return;}if(v.role=="bar")Activity(a,"order","order",2);else{string action=v.role=="bed"?"sleep":v.role=="sun"?"sunbathe":v.role=="warm"?"rest":v.role=="seat"?"sit":v.role=="reception"?"greet":a.slotAction;Activity(a,"activity",action,v.role=="reception"?2:action=="sleep"?11:7);}a.view.facing=(float)Math.Atan2(v.x-a.view.x,v.z-a.view.z);}
 void ChooseCleaning(Actor a){foreach(var r in Hotel().rooms){if(!Hotel().dirty.TryGetValue(r.id,out bool dirty)||!dirty||!RoomStatus(r.id).ready)continue;foreach(var bed in Hotel().objects.Where(o=>o.room==r.id&&Catalog.Find(o.itemId).role=="bed"))foreach(var p in Approaches(bed,State.currentHotel)){string key=SlotKey(p);if(reservations.ContainsKey(key)||!Free(p,a,true))continue;var route=ActivityRoute(a.Position,p);if(route.Count==0)continue;Release(a);a.slot=key;reservations[key]=a.view.catId;a.cleanRoom=r.id;a.route=route;a.waypoint=0;Activity(a,"walk_clean","walk",0);return;}}Activity(a,"idle","rest",2);}
 void CancelMoment(){if(momentA!=null){momentA.view.speech="";momentA.view.gesture="";}if(momentB!=null){momentB.view.speech="";momentB.view.gesture="";}momentA=momentB=null;momentRemaining=0;nextMoment=Math.Max(nextMoment,socialClock+8);}
 void AdvanceMoments(float dt){socialClock+=dt;if(momentRemaining>0){momentRemaining-=dt;if(momentRemaining<=0||!actors.Contains(momentA)||!actors.Contains(momentB)||!new[]{"idle","activity","sit"}.Contains(momentA.phase)||!new[]{"idle","activity","sit"}.Contains(momentB.phase)||momentA.Position.Distance(momentB.Position)>3.2f){CancelMoment();return;}float elapsed=momentLines.Count*3.4f-momentRemaining;int line=(int)(elapsed/3.4f);float phase=elapsed%3.4f;momentA.view.speech=momentB.view.speech="";momentA.view.gesture=momentB.view.gesture=elapsed<.65f?"wave":"listen";if(line<momentLines.Count&&phase<3.1f){var speaker=line%2==0?momentA:momentB;speaker.view.speech=(string)momentLines[line];speaker.view.gesture=line==momentLines.Count-1?"happy":"talk";}return;}if(socialClock<nextMoment)return;var available=actors.Where(a=>a.view.catId<1000&&a.checkedIn&&(a.phase=="idle"||a.phase=="activity"||a.phase=="sit")&&new[]{"rest","sit","loaf","sunbathe","sleep","drink","play","peek","scratch"}.Contains(a.view.action)&&(!socialCooldown.TryGetValue(a.view.catId,out float until)||socialClock>=until)).OrderBy(a=>a.view.catId).ToArray();foreach(var a in available)foreach(var b in available){if(a.view.catId>=b.view.catId)continue;string key=a.view.catId+":"+b.view.catId;if(pairCooldown.TryGetValue(key,out float until)&&socialClock<until)continue;float distance=a.Position.Distance(b.Position);if(distance<.72||distance>3.2)continue;var ar=Hotel().rooms.Find(r=>r.kind!="terrace"&&Rect(r).Has(a.view.x,a.view.z));var br=Hotel().rooms.Find(r=>r.kind!="terrace"&&Rect(r).Has(b.view.x,b.view.z));if(ar!=br)continue;if(Hotel().rooms.Any(r=>r!=ar&&r.kind!="terrace"&&Hits(a.Position,b.Position,Rect(r))))continue;
 string topic=momentSerial%2==0?State.cats[a.view.catId].preference:State.cats[b.view.catId].preference;if(State.cats[a.view.catId].friend==b.view.catId&&momentSerial%3==0)topic="social";foreach(var o in Hotel().objects){if(!new[]{"fountain","fireplace","milkshake_counter"}.Contains(o.itemId))continue;var box=Rect(o);if(new LotPoint(box.x+box.w/2,box.z+box.d/2).Distance(a.Position)<3.5){topic=o.itemId=="fountain"?"fountain":o.itemId=="fireplace"?"warm":"food";break;}}
 var dialogue=Content.Raw["dialogue"]??new JArray();var options=dialogue.Where(row=>(string)row[1]==topic&&!recentDialogue.Contains((string)row[0])).ToArray();if(options.Length==0)options=dialogue.Where(row=>(string)row[1]=="social"&&!recentDialogue.Contains((string)row[0])).ToArray();if(options.Length==0)continue;var selected=options[(momentSerial+a.view.catId*3+b.view.catId)%options.Length];recentDialogue.Add((string)selected[0]);if(recentDialogue.Count>8)recentDialogue.RemoveAt(0);momentLines=new JArray(selected.Skip(2));momentSerial++;momentA=a;momentB=b;momentRemaining=momentLines.Count*3.4f;socialCooldown[a.view.catId]=socialClock+momentRemaining+45;socialCooldown[b.view.catId]=socialClock+momentRemaining+45;pairCooldown[key]=socialClock+momentRemaining+90;nextMoment=socialClock+momentRemaining+20+momentSerial*7%16;return;}}
}
}




