using System;using System.Linq;using Newtonsoft.Json;using Newtonsoft.Json.Linq;
namespace Purrington.Domain {
internal static class StrictSaveJson {
 static void Require(bool condition){if(!condition)throw new JsonSerializationException("Invalid parity hotel save schema.");}
 static void Fields(JToken t,string names,JTokenType type,bool optional=false){Require(t is JObject);foreach(string name in names.Split(',')){var v=t[name];if(v==null&&optional)continue;Require(v!=null&&v.Type==type);}}
 static void Numbers(JToken t,string names,bool integer=false,bool optional=false){foreach(string name in names.Split(',')){var v=t[name];if(v==null&&optional)continue;Require(v!=null&&(v.Type==JTokenType.Integer||v.Type==JTokenType.Float));double n=(double)v;Require(!double.IsNaN(n)&&!double.IsInfinity(n)&&(!integer||n==Math.Floor(n)));}}
 static void Object(JToken o){Fields(o,"id,itemId,room",JTokenType.String);Numbers(o,"x,z,paid");Numbers(o,"rotation",true);Numbers(o,"floor",true,true);}
 public static HotelState Read(string json){var j=JObject.Parse(json);Numbers(j,"version,currentHotel,nextId,lastSeen",true);Numbers(j,"coins,elapsed,pendingCoins");Fields(j,"hotels,storage,cats,entitlements",JTokenType.Array);Fields(j,"settings",JTokenType.Object);Require(j["hotels"].Count()==4&&j["cats"].Count()==18);foreach(var h in j["hotels"]){Fields(h,"owned",JTokenType.Boolean);Fields(h,"maid",JTokenType.Boolean,true);Fields(h,"plots,rooms,objects,upgrades,staff",JTokenType.Array);Fields(h,"paths",JTokenType.Object);Fields(h,"dirty",JTokenType.Object,true);Numbers(h,"level,visits,happy,cleaned,purchases",true);Numbers(h,"dirtCursor",true,true);Numbers(h,"dirtClock",false,true);foreach(var d in ((JObject)h["dirty"]??new JObject()).Properties())Require(d.Value.Type==JTokenType.Boolean);foreach(var p in h["paths"].Children<JProperty>()){Fields(p.Value,"style",JTokenType.String);Numbers(p.Value,"paid");}foreach(var n in h["upgrades"].Concat(h["staff"]))Require((n.Type==JTokenType.Integer||n.Type==JTokenType.Float)&&(double)n==Math.Floor((double)n));foreach(var p in h["plots"])Require(p.Type==JTokenType.String);foreach(var r in h["rooms"]){Fields(r,"id,name,kind",JTokenType.String);Numbers(r,"x,z,width,depth,rotation",true);Numbers(r,"floor",true,true);Numbers(r,"paid");}Fields(h,"floors",JTokenType.Array,(double)j["version"]<3);foreach(var f in (JArray)h["floors"]??new JArray()){Fields(f,"cells,edges",JTokenType.Object);Numbers(f,"level",true);foreach(var c in f["cells"].Children<JProperty>())Require(c.Value.Type==JTokenType.Integer||c.Value.Type==JTokenType.Float);foreach(var e in f["edges"].Children<JProperty>()){Fields(e.Value,"kind,room",JTokenType.String);Numbers(e.Value,"paid");}}foreach(var o in h["objects"])Object(o);}foreach(var o in j["storage"])Object(o);foreach(var c in j["cats"]){Fields(c,"name,preference",JTokenType.String);Fields(c,"known",JTokenType.Boolean);Numbers(c,"id,bond",true);Numbers(c,"lastCare");Numbers(c,"friend",true,true);}var settings=(JObject)j["settings"];foreach(var p in settings.Properties()){Require(new[]{"motion","music","sound","exterior","evening","godMode","assistedCare","textScale"}.Contains(p.Name));if(p.Name=="textScale")Numbers(settings,"textScale");else Require(p.Value.Type==JTokenType.Boolean);}foreach(var e in j["entitlements"])Require(e.Type==JTokenType.String);var state=j.ToObject<HotelState>();foreach(var c in state.cats)if(string.IsNullOrEmpty(c.favoriteAction)&&ParityContent.Current!=null)c.favoriteAction=(string)ParityContent.Current.Cats[c.id]["favoriteAction"];return state;}
}
public sealed partial class HotelModel {
 public bool Restore(HotelState candidate){if(candidate!=null){candidate=Copy(candidate);ShellMigration.Upgrade(candidate);}if(!Valid(candidate))return false;State=Copy(candidate);undo.Clear();redo.Clear();Invalidate();ResetLife();Changed?.Invoke();return true;}
 public bool RestoreJson(string json){try{return Restore(new NewtonsoftSaveCodec().Deserialize(json));}catch(JsonException){return false;}catch(ArgumentException){return false;}}
}
}
