using System;
using System.Collections.Generic;
using UnityEngine;
namespace Purrington.Presentation {
public sealed class GodotObjectMotion {
 readonly Transform root,part; readonly string shape; readonly Vector2 footprint;readonly Vector3 restPos,restScale;readonly Quaternion restRot;readonly Vector3 effectAnchor;readonly Dictionary<Renderer,Color> lampColors=new Dictionary<Renderer,Color>();readonly MaterialPropertyBlock tint=new MaterialPropertyBlock();readonly Dictionary<string,Transform[]> effects=new Dictionary<string,Transform[]>();readonly GodotGeometry geometry;float clock,phase,last,burst=-1,lampGlow=-1;string action="",token="";bool previousMotion=true;public int BurstCount{get;private set;}
 public GodotObjectMotion(GodotGeometry g,Transform root,string shape,Vector2 footprint,string id){geometry=g;this.root=root;this.shape=shape;this.footprint=footprint;foreach(var t in root.GetComponentsInChildren<Transform>(true))if(t.name=="LifePart")part=t;if(!part)part=new GameObject("LifePart").transform;if(part.parent==null)part.SetParent(root,false);restPos=part.localPosition;restScale=part.localScale;restRot=part.localRotation;var anchor=part.GetComponent<GodotNodeMetadata>()?.Values?["effect_anchor"];if(anchor!=null)effectAnchor=new Vector3((float)anchor[0],(float)anchor[1],(float)anchor[2]);if(shape=="lamp"||shape=="garden_lamp")foreach(var renderer in part.GetComponentsInChildren<MeshRenderer>()){lampColors[renderer]=renderer.sharedMaterial.color;renderer.sharedMaterial=geometry.GlowTwin(renderer.sharedMaterial);}uint hash=5381;foreach(char c in id)hash=hash*33+c;phase=(hash%4096)/4096f*Mathf.PI*2;
 foreach(var t in root.GetComponentsInChildren<Transform>(true))if(t.name=="LifeMotion"||t.name=="VoxelSpillways")t.gameObject.SetActive(false);
 switch(shape){case "fireplace":Make("flames",3,"#F0A830");Make("embers",8,"#F0A830");break;case "fountain":Make("spout",5,"#a8e9df");Make("splash",12,"#83d4d0");Make("spill",56,"#74c5c5");break;case "milkshake_counter":Make("foam",8,"#fff1df");break;case "scratch":Make("fibers",10,"#d8bd91");break;case "litter":Make("burst",12,"#d4b27e");break;}}
 void Make(string key,int count,string color){var list=new Transform[count];for(int i=0;i<count;i++){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name=key+" "+i;go.transform.SetParent(root,false);UnityEngine.Object.Destroy(go.GetComponent<Collider>());go.GetComponent<MeshRenderer>().sharedMaterial=geometry.Material(color);go.GetComponent<MeshRenderer>().shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;list[i]=go.transform;go.SetActive(false);}effects[key]=list;}
 void Set(string key,int i,Vector3 p,Vector3 size){var t=effects[key][i];t.gameObject.SetActive(true);t.localPosition=p;t.localScale=size;}void Hide(string key){if(effects.TryGetValue(key,out var list))foreach(var t in list)t.gameObject.SetActive(false);}void Restore(){part.localPosition=restPos;part.localRotation=restRot;part.localScale=restScale;}
 public void Activity(string next,float elapsed,string nextToken){bool changed=next!=action||token!=nextToken||elapsed<last;if(changed){Hide("foam");Hide("fibers");Hide("burst");burst=-1;}else if(previousMotion&&shape=="litter"&&next=="dig")foreach(float marker in new[]{1.1f,2.3f,3.5f})if(last<marker&&elapsed>=marker){burst=marker;BurstCount++;}action=next;token=nextToken;last=elapsed;}
 public void Advance(float delta,bool motion,bool visible=true){previousMotion=motion&&visible;if(!visible){foreach(var key in effects.Keys)Hide(key);return;}if(!motion){Restore();foreach(var key in new[]{"embers","splash","foam","fibers","burst"})Hide(key);burst=-1;if(shape=="fireplace")Fire(0,true);if(shape=="fountain")Spill(0);NightLamps();return;}clock+=delta;float t=clock+phase;Restore();
 switch(shape){case "fireplace":Fire(t,false);break;case "fountain":Spill(clock);for(int i=0;i<5;i++)Set("spout",i,new Vector3(0,2.15f+i*.095f+Mathf.Sin(t*3.5f+i*.4f)*.022f,0),new Vector3(.07f,.12f,.07f));for(int i=0;i<12;i++){float p=Mathf.Repeat(t*.7f+i/12f,1),a=i*Mathf.PI*2/12,r=.09f+p*.25f;Set("splash",i,new Vector3(Mathf.Cos(a)*r,1.91f+Mathf.Sin(p*Mathf.PI)*.13f,Mathf.Sin(a)*r),Vector3.one*.045f);}break;
 case "plant":case "garden_planter":case "shrub":case "flowers":case "flower_bed":case "tree":part.localRotation=restRot*Quaternion.Euler(0,0,Mathf.Sin(t*.72f)*.025f*Mathf.Rad2Deg);break;
 case "lamp":case "garden_lamp":part.localScale=restScale*(1+Mathf.Sin(t*1.1f)*.012f);float glow=.03f+.055f*(.5f+.5f*Mathf.Sin(t*1.1f));foreach(var lamp in lampColors){tint.SetColor("_BaseColor",Color.Lerp(lamp.Value,Color.white,glow));lamp.Key.SetPropertyBlock(tint);}break;}
 bool bed=Array.IndexOf(new[]{"mat","sun_cushion","heated","blanket","cave","canopy_bed","cloud_sofa","lounge_sofa"},shape)>=0;
 if(bed&&(action=="sleep"||action=="rest"||action=="knead"))part.localScale=new Vector3(restScale.x,restScale.y*(.965f+(action=="knead"?Mathf.Sin(t*4)*.012f:0)),restScale.z);
 if(shape=="milkshake_counter"&&action=="serve"){part.localPosition=restPos+new Vector3(Mathf.Sin(t*34)*.018f,0,Mathf.Cos(t*29)*.012f);for(int i=0;i<8;i++)Set("foam",i,effectAnchor+new Vector3((i%3-1)*.045f,Mathf.Repeat(t*.9f+i/8f,1)*.16f,(i%2-.5f)*.06f),Vector3.one*.035f);}
 if(shape=="box"&&action=="peek")part.localRotation=restRot*Quaternion.Euler((-.18f+Mathf.Sin(t*5)*.12f)*Mathf.Rad2Deg,0,0);
 if(shape=="scratch"&&action=="scratch"){part.localRotation=restRot*Quaternion.Euler(0,0,Mathf.Sin(t*13)*.035f*Mathf.Rad2Deg);for(int i=0;i<10;i++)Set("fibers",i,new Vector3((i%5-2)*.035f,.3f+(i/5)*.24f,(i%2-.5f)*.14f),new Vector3(.018f,.045f,.018f));}
 if((shape=="tunnel"||shape=="playpen")&&action=="play")part.localPosition=restPos+Vector3.up*Mathf.Abs(Mathf.Sin(t*5))*.13f;
 if(shape=="reception_counter"&&action=="greet")part.localPosition=restPos+Vector3.up*Mathf.Abs(Mathf.Sin(t*8))*.07f;
 if(burst>=0){float age=last-burst;if(age<0||age>=.58f){Hide("burst");burst=-1;}else for(int i=0;i<12;i++){float a=i*Mathf.PI*2/12+burst,r=.09f+i%4*.035f+age*.38f,s=(.035f+i%2*.018f)*(1-age/.58f);Set("burst",i,new Vector3(Mathf.Cos(a)*r,.45f+Mathf.Sin(age/.58f*Mathf.PI)*.2f+i%3*.035f,footprint.y*.42f+Mathf.Sin(a)*r),Vector3.one*s);}}
 NightLamps();
 }
 // Lamp parts get an emissive twin cloned from WorldGlowMaterial (the build keeps its _EMISSION variant); the block only carries the color.
 void NightLamps(){if(lampColors.Count==0||WorldLighting.Glow==lampGlow)return;lampGlow=WorldLighting.Glow;var glow=GodotGeometry.GlowColor*(WorldLighting.Glow*2.6f);foreach(var lamp in lampColors){lamp.Key.GetPropertyBlock(tint);tint.SetColor("_EmissionColor",glow);lamp.Key.SetPropertyBlock(tint);}}
 void Spill(float t){for(int i=0;i<56;i++){int tier=i/28,side=(i/7)%4,step=i%7;float f=Mathf.Repeat(step/7f+t*.62f,1),top=tier==1?1.87f:1.2f,bottom=tier==1?1.2f:.36f,r=(tier==1?.14f:.32f)+f*.075f,s=.065f+i%3*.016f;var p=new Vector3(0,Mathf.Lerp(top,bottom,f*f),0);if(side<2)p.x=footprint.x*r*(side==0?1:-1);else p.z=footprint.y*r*(side==2?1:-1);Set("spill",i,p,new Vector3(s,s*1.35f,s));}}
 void TintFlame(int i,int color){ColorUtility.TryParseHtmlString(new[]{"#FFD16F","#F0A830","#FFD16F"}[color],out var c);tint.SetColor("_BaseColor",c);effects["flames"][i].GetComponent<MeshRenderer>().SetPropertyBlock(tint);}
 void Fire(float t,bool still){for(int i=0;i<3;i++){float h=still?new[]{.28f,.34f,.25f}[i]:.22f+.12f*(.5f+.5f*Mathf.Sin(t*6.2f+i*1.8f));TintFlame(i,still?i:((int)(t*8)+i)%3);Set("flames",i,new Vector3((-.18f+i*.205f)*footprint.x,.2f+h*.5f,footprint.y*.5f),new Vector3(.13f,h,.085f));}if(still)return;int count=5+(int)(t*1.7f)%4;for(int i=0;i<8;i++){if(i>=count){effects["embers"][i].gameObject.SetActive(false);continue;}float f=Mathf.Repeat(t*.38f+i*.137f,1);Set("embers",i,new Vector3(((i*5)%7/6f-.5f)*.48f,.35f+f*.62f,footprint.y*.51f),Vector3.one*(.025f+.014f*(i%2)));}}
}
}

