using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using UnityEngine;
namespace Purrington.Presentation {public sealed partial class VoxelWorld {
 Transform careStage,careProp,careCushion;GodotCatRig careRig;int careId=-1,careMap=-1;readonly Vector3 careOrigin=new Vector3(600,0,600);string careToolId="pet";Vector3 yarnVelocity;bool careHeld,careContact;float careClock,carePlayClock,careAutomatic,furClock;readonly List<Fur> fur=new List<Fur>();sealed class Fur{public Transform node;public Vector3 start;public float time;}
 public void SetCareMode(int catId,bool active){if(!active){if(care){focus=savedFocus;zoom=savedZoom;}care=false;careHeld=careContact=false;if(careStage)careStage.gameObject.SetActive(false);UpdateCamera();return;}if(!care){savedFocus=focus;savedZoom=zoom;}if(!careStage||careId!=catId||careMap!=currentMap){DisposeNode(careStage);careStage=Group(renderRoot,"Care room");careStage.localPosition=careOrigin;var bindings=new Dictionary<string,Transform>();geometry.Build(careStage,(JObject)geometry.Map(currentMap)["care"],bindings);foreach(var t in careStage.GetComponentsInChildren<Transform>(true))if(t.name=="CareCushion")careCushion=t;careRig=new GodotCatRig(geometry,careStage,"cats",catId.ToString(),catId);careRig.Root.localPosition=Vector3.zero;careRig.Root.localScale=Vector3.one*1.3f;careProp=Group(careStage,"Care tool");careId=catId;careMap=currentMap;SelectCareTool("pet");}care=true;careStage.gameObject.SetActive(true);focus=careOrigin+new Vector3(0,.85f,0);zoom=Mathf.Max(1.45f,1.2f/Mathf.Max(.3f,WorldCamera.aspect));UpdateCamera();}
 public bool CareHit(Vector2 screen){if(!care||careRig==null)return false;var ray=WorldCamera.ScreenPointToRay(screen);foreach(var r in careRig.Root.GetComponentsInChildren<MeshRenderer>()){if(!r.enabled||!r.gameObject.activeInHierarchy)continue;var filter=r.GetComponent<MeshFilter>();if(!filter)continue;var local=new Ray(r.transform.InverseTransformPoint(ray.origin),r.transform.InverseTransformVector(ray.direction));if(filter.sharedMesh.bounds.IntersectRay(local))return true;}return false;}
 Vector3 CarePoint(Vector2 screen,float y){var p=GroundPoint(screen,y)-careOrigin;return new Vector3(Mathf.Clamp(p.x,-1.05f,1.05f),y,Mathf.Clamp(p.z,-.55f,.9f));}
 public void CarePointer(string tool,Vector2 screen,string phase,Vector2 velocity){if(!care)return;if(tool=="feather")tool="wand";if(phase=="select"||careToolId!=tool){SelectCareTool(tool);if(phase=="select")return;}if(phase=="cancel"){careHeld=careContact=false;carePlayClock=0;yarnVelocity=Vector3.zero;if(tool=="brush")careProp.gameObject.SetActive(false);return;}
 if(phase=="begin"){careHeld=true;careClock=carePlayClock=careAutomatic=0;yarnVelocity=Vector3.zero;}
 if(phase=="begin"||phase=="move"){if(tool=="pet"||tool=="brush"){careContact=CareHit(screen);if(careContact){careRig.Stroke=Vector2.ClampMagnitude(velocity/600,1);if(careRig.Reaction=="")careRig.React(tool=="brush"?"brush":"purr",2);}if(tool=="brush"){careProp.gameObject.SetActive(careContact);var ray=WorldCamera.ScreenPointToRay(screen);float d=(-careOrigin.z-.9f-ray.origin.z)/ray.direction.z;careProp.position=ray.GetPoint(d)+Vector3.right*.15f;}}else if(tool=="wand"||tool=="yarn"){careProp.gameObject.SetActive(true);careProp.localPosition=CarePoint(screen,tool=="wand"?.8f:.16f);}else if(phase=="begin")UseCarePlacement(tool,CarePoint(screen,0));}
 if(phase=="end"){if(tool=="yarn"&&careHeld){yarnVelocity=(CarePoint(screen+Vector2.ClampMagnitude(velocity,1500)*.15f,.16f)-careProp.localPosition)*4;if(yarnVelocity.magnitude<.1f)yarnVelocity=new Vector3(.85f,0,.25f);carePlayClock=3.5f;}else if(tool=="wand"&&careHeld)carePlayClock=1.2f;careHeld=careContact=false;if(tool=="brush")careProp.gameObject.SetActive(false);}}
 public void PlayCare(string tool){if(!care)return;if(tool=="feather")tool="wand";if(careToolId!=tool)SelectCareTool(tool);careClock=0;if(tool=="pet"||tool=="brush"){careRig.React(tool=="brush"?"brush":"purr",2);if(!careHeld){careAutomatic=2;careContact=true;if(tool=="brush"){careProp.gameObject.SetActive(true);careProp.localPosition=new Vector3(.55f,.95f,.9f);}}}else if(tool=="cushion"||tool=="box")UseCarePlacement(tool,Vector3.zero);else if(!careHeld){careProp.gameObject.SetActive(true);careProp.localPosition=new Vector3(.75f,tool=="wand"?.85f:.16f,.2f);carePlayClock=3.5f;if(tool=="yarn")yarnVelocity=new Vector3(-.9f,0,.2f);}}
 void UseCarePlacement(string tool,Vector3 position){careProp.localPosition=position;if(tool=="cushion"){careCushion.gameObject.SetActive(true);careCushion.localPosition=position;careProp.gameObject.SetActive(false);careRig.Root.localPosition=position+Vector3.up*.14f;careRig.React("settle",4);}else{careProp.gameObject.SetActive(true);careRig.Root.localPosition=position;careRig.React("peek",4);}}
 void SelectCareTool(string tool){careToolId=tool;careHeld=careContact=false;carePlayClock=careAutomatic=careClock=0;yarnVelocity=Vector3.zero;careRig.Root.localPosition=Vector3.zero;careRig.Root.localRotation=Quaternion.identity;careRig.Reaction="";careRig.Stroke=Vector2.zero;if(careCushion)careCushion.gameObject.SetActive(false);foreach(Transform t in careProp)DisposeNode(t);careProp.localPosition=Vector3.zero;careProp.gameObject.SetActive(false);
 geometry.Build(careProp,geometry.Recipe("careTools",tool));}
 Transform Ball(Transform parent,Vector3 at,float radius,string color,Vector3 scale){var g=GameObject.CreatePrimitive(PrimitiveType.Sphere);g.transform.SetParent(parent,false);g.transform.localPosition=at;g.transform.localScale=scale*radius*2;Destroy(g.GetComponent<Collider>());g.GetComponent<MeshRenderer>().sharedMaterial=geometry.Material(color);return g.transform;}
 void AnimateCare(){if(!care||careRig==null)return;float dt=Time.deltaTime;bool motion=model.State.settings.motion;careClock+=dt;careRig.Advance(dt,motion,"rest",false,careToolId=="box"&&careProp.gameObject.activeSelf?"peek":"",careClock);if(careAutomatic>0){careAutomatic=Mathf.Max(0,careAutomatic-dt);if(careAutomatic==0&&!careHeld)careContact=false;}if(careContact){if(careRig.Reaction=="")careRig.React(careToolId=="brush"?"brush":"purr",2);if(careToolId=="brush"&&motion){if(careAutomatic>0&&!careHeld){var p=careProp.localPosition;p.y=.95f+Mathf.Sin(careClock*6)*.12f;careProp.localPosition=p;}furClock+=dt;if(furClock>.25f){furClock=0;var p=careProp.localPosition+Vector3.left*.1f;fur.Add(new Fur{node=Ball(careStage,p,.025f,Shade((string)model.Content.Cats[careId]["color"],.3f),Vector3.one),start=p});}}}
 if((careToolId=="wand"||careToolId=="yarn")&&(careHeld||carePlayClock>0)){carePlayClock=Mathf.Max(0,carePlayClock-dt);if(motion){if(careToolId=="yarn"&&!careHeld){var p=careProp.localPosition+yarnVelocity*dt;if(Mathf.Abs(p.x)>1.05f)yarnVelocity.x*=-.7f;if(p.z<-.55f||p.z>.9f)yarnVelocity.z*=-.7f;p.x=Mathf.Clamp(p.x,-1.05f,1.05f);p.z=Mathf.Clamp(p.z,-.55f,.9f);careProp.localPosition=p;yarnVelocity=Vector3.MoveTowards(yarnVelocity,Vector3.zero,dt*.22f);}var target=careProp.localPosition;careRig.Root.localPosition=Vector3.MoveTowards(careRig.Root.localPosition,new Vector3(target.x*.65f,0,target.z*.45f),dt*.75f);careRig.Bindings["head"].localRotation=Quaternion.Euler((careToolId=="wand"?-.12f:.3f)*Mathf.Rad2Deg,Mathf.Clamp((target.x-careRig.Root.localPosition.x)*.6f,-.6f,.6f)*Mathf.Rad2Deg,0);var body=careRig.Bindings["body"];body.localPosition=Vector3.up*(careToolId=="wand"?Mathf.Max(0,Mathf.Sin(careClock*3))*.18f:Mathf.Abs(Mathf.Sin(careClock*10))*.035f);for(int i=0;i<4;i++)if(careToolId=="yarn"||i==1)careRig.Bindings["legs."+i].localRotation=Quaternion.Euler((careToolId=="yarn"?Mathf.Sin(careClock*10+i*2)*.35f:-Mathf.Abs(Mathf.Sin(careClock*6))*.8f)*Mathf.Rad2Deg,0,0);}}
 for(int i=fur.Count-1;i>=0;i--){var f=fur[i];if(!f.node){fur.RemoveAt(i);continue;}f.time+=dt;float p=Mathf.Clamp01(f.time/.55f);f.node.localPosition=f.start+new Vector3(.15f,-.35f,.05f)*p;f.node.localScale=Vector3.one*.05f*(1-p);if(p>=1){DisposeNode(f.node);fur.RemoveAt(i);}}
 }
 void OnApplicationFocus(bool focused){if(!focused){careHeld=careContact=false;carePlayClock=0;yarnVelocity=Vector3.zero;}}
}}



