using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;
using Purrington.Domain;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
namespace Purrington.Presentation {
public sealed partial class VoxelWorld:MonoBehaviour {
 public const float Unit=1.1f;const float GroundY=.18f;
 public Camera WorldCamera{get;private set;}public event Action<int> CatSelected;public event Action<Vector3> GroundClicked;public event Action<string> ObjectSelected;
 HotelModel model;GodotGeometry geometry;Transform renderRoot,scenery,layout,preview;Light sun;string signature;int currentMap=-1;bool exterior;
 Rect worldRect;bool manualCamera;Bounds? lastFitBounds;Vector3 focus,savedFocus;float zoom=18,savedZoom,pinchDistance;readonly Quaternion angle=Quaternion.Euler(36.59f,315,0);
 bool blocked,pressed,dragged,care,carePressed,pinchActive,pinchOwned;int pinchFirstId,pinchSecondId;Vector2 down,previous;readonly Dictionary<int,bool> touchStartedOnWorld=new Dictionary<int,bool>();readonly List<int> endedTouchIds=new List<int>();
 readonly Dictionary<string,Transform> objects=new Dictionary<string,Transform>(),rooms=new Dictionary<string,Transform>();readonly Dictionary<string,GodotObjectMotion> effects=new Dictionary<string,GodotObjectMotion>();readonly Dictionary<string,GodotCatRig> actors=new Dictionary<string,GodotCatRig>();
 readonly Dictionary<int,NeighborhoodView> neighborhoods=new Dictionary<int,NeighborhoodView>();
 public void Initialize(HotelModel hotel){model=hotel;geometry=new GodotGeometry();renderRoot=Group(transform,"Godot coordinate space");renderRoot.localScale=new Vector3(1,1,-1);WorldCamera=new GameObject("Isometric camera").AddComponent<Camera>();WorldCamera.transform.SetParent(transform);WorldCamera.tag="MainCamera";WorldCamera.orthographic=true;WorldCamera.nearClipPlane=.1f;WorldCamera.farClipPlane=500;WorldCamera.clearFlags=CameraClearFlags.SolidColor;WorldCamera.allowHDR=true;WorldCamera.allowMSAA=true;WorldCamera.GetUniversalAdditionalCameraData().renderPostProcessing=true;WorldCamera.gameObject.AddComponent<AudioListener>();sun=new GameObject("Warm afternoon sun").AddComponent<Light>();sun.transform.SetParent(transform);sun.type=LightType.Directional;sun.transform.rotation=Quaternion.Euler(46,28,0);sun.shadows=LightShadows.Soft;sun.shadowStrength=.48f;sun.shadowBias=.045f;sun.shadowNormalBias=.45f;RenderSettings.ambientMode=AmbientMode.Flat;model.Changed+=Refresh;Refresh();FocusHotel();}
 void OnDestroy(){if(model!=null)model.Changed-=Refresh;geometry?.Dispose();}
 public void SetInputBlocked(bool value){blocked=value;if(value)pressed=false;}
 public Vector3 ScreenToGround(Vector2 screen){var p=GroundPoint(screen,GroundY);return new Vector3(p.x/Unit,p.y,p.z/Unit);}
 Vector3 GroundPoint(Vector2 screen,float y){var ray=WorldCamera.ScreenPointToRay(screen);return new Plane(Vector3.up,new Vector3(0,y,0)).Raycast(ray,out float distance)?ToAuthored(ray.GetPoint(distance)):focus;}
 public void FocusHotel(){if(care)SetCareMode(0,false);FitHotel();}
 public void FitHotel(){townFollowing=false;Bounds? bounds=null;foreach(var r in model.State.rooms){HotelModel.RoomSize(r,out float w,out float d);var b=new Bounds(new Vector3((r.x+w*.5f)*Unit,1.2f,(r.z+d*.5f)*Unit),new Vector3(w*Unit,2.4f,d*Unit));if(bounds.HasValue){var n=bounds.Value;n.Encapsulate(b);bounds=n;}else bounds=b;}foreach(var o in model.State.objects){HotelModel.Size(o,out float w,out float d);var b=new Bounds(new Vector3((o.x+w*.5f)*Unit,.7f,(o.z+d*.5f)*Unit),new Vector3(w*Unit,1.4f,d*Unit));if(bounds.HasValue){var n=bounds.Value;n.Encapsulate(b);bounds=n;}else bounds=b;}FocusBounds(bounds??PropertyBounds());}
 public void FocusRoom(string id){if(rooms.TryGetValue(id,out var r))FocusBounds(RenderBounds(r));}public void FocusObject(string id){if(objects.TryGetValue(id,out var o))FocusBounds(RenderBounds(o));}
 static Vector3 ToAuthored(Vector3 point){return new Vector3(point.x,point.y,-point.z);}
 static Bounds RenderBounds(Transform t){var result=new Bounds(t.position,Vector3.zero);foreach(var r in t.GetComponentsInChildren<Renderer>())result.Encapsulate(r.bounds);return new Bounds(ToAuthored(result.center),result.size);}
 void FocusBounds(Bounds bounds){manualCamera=false;lastFitBounds=bounds;focus=bounds.center;float x=0,y=0;var inv=Quaternion.Inverse(angle);for(int i=0;i<8;i++){var v=inv*ToAuthored(Vector3.Scale(bounds.extents,new Vector3((i&1)==0?-1:1,(i&2)==0?-1:1,(i&4)==0?-1:1)));x=Mathf.Max(x,Mathf.Abs(v.x));y=Mathf.Max(y,Mathf.Abs(v.y));}var visible=VisibleWorldRect();zoom=Mathf.Clamp(Mathf.Max(y*Screen.height/visible.height,x*Screen.height/visible.width)*1.06f,3,90);UpdateCamera();}
 Bounds PropertyBounds(){var a=model.Map()["base"];return new Bounds(new Vector3(((float)a[0]+(float)a[2]/2)*Unit,0,((float)a[1]+(float)a[3]/2)*Unit),new Vector3((float)a[2]*Unit,3,(float)a[3]*Unit));}
 void LimitCamera(){var b=PropertyBounds();if(townMode){b.Encapsulate(new Vector3(42*Unit,0,40*Unit));b.Encapsulate(new Vector3(20*Unit,0,-8*Unit));}focus.x=Mathf.Clamp(focus.x,b.min.x-8,b.max.x+8);focus.z=Mathf.Clamp(focus.z,b.min.z-8,b.max.z+8);}
 public void SetWorldRect(Rect rect){if(rect.width<1||rect.height<1)return;if(worldRect==rect)return;worldRect=rect;if(care)zoom=Mathf.Max(1.7f,1.65f*rect.height/Mathf.Max(1,rect.width))*Screen.height/rect.height;else if(!manualCamera)FocusBounds(lastFitBounds??PropertyBounds());UpdateCamera();}
 Rect VisibleWorldRect(){return worldRect.width>1&&worldRect.height>1?worldRect:new Rect(0,0,Screen.width,Screen.height);}
 void UpdateCamera(){if(!WorldCamera)return;WorldCamera.transform.rotation=care?Quaternion.LookRotation(new Vector3(-1.65f,-1.65f,5)):angle;WorldCamera.transform.position=ToAuthored(focus)-WorldCamera.transform.forward*85;WorldCamera.orthographicSize=zoom;var rect=VisibleWorldRect();var offset=rect.center-new Vector2(Screen.width/2f,Screen.height/2f);WorldCamera.transform.position-=(WorldCamera.transform.right*offset.x+WorldCamera.transform.up*offset.y)*(zoom*2/Mathf.Max(1,Screen.height));}
 public void SetCutaway(bool value){exterior=!value;foreach(var r in rooms.Values){var full=r.Find("FullWalls");var cut=r.Find("CutawayWalls");var roof=r.Find("Roof");if(full)full.gameObject.SetActive(exterior);if(cut)cut.gameObject.SetActive(!exterior);if(roof)roof.gameObject.SetActive(exterior);}}
 public void SetEvening(bool value){sun.color=Hex(value?"FFD5A8":"FFF0D5");sun.intensity=value?.65f:1.12f;RenderSettings.ambientLight=Hex(value?"A0ACBB":"E9E0C9")*(value?.65f:.78f);RenderSettings.ambientSkyColor=Hex(value?"7A8EA6":"D7DCC6")*.6f;RenderSettings.ambientEquatorColor=Hex(value?"6A8393":"E9DFC6")*.48f;RenderSettings.ambientGroundColor=Hex("738448")*.30f;WorldCamera.backgroundColor=Hex(value?"9AA8AE":new[]{"E5D6B9","C6D5D2","D2D9BB","E2E4DE"}[model.State.currentHotel]);}
 void Refresh(){bool mapChanged=currentMap!=model.State.currentHotel;if(mapChanged){currentMap=model.State.currentHotel;signature=null;DisposeNode(scenery);scenery=Group(renderRoot,"Destination "+currentMap);geometry.Build(scenery,(JObject)geometry.Map(currentMap)["groundWithoutParcels"]);foreach(var n in neighborhoods.Values)n.Root.gameObject.SetActive(false);if(!neighborhoods.TryGetValue(currentMap,out var neighborhood)){neighborhood=new NeighborhoodView(geometry,renderRoot,currentMap);neighborhoods.Add(currentMap,neighborhood);}neighborhood.Root.gameObject.SetActive(true);foreach(var a in actors.Values)DisposeNode(a.Root);actors.Clear();}
 var s=new StringBuilder();s.Append(currentMap);foreach(var r in model.State.rooms)s.Append('|').Append(r.id).Append(',').Append(r.name).Append(',').Append(r.kind).Append(',').Append(r.x).Append(',').Append(r.z).Append(',').Append(r.width).Append(',').Append(r.depth).Append(',').Append(r.rotation);foreach(var o in model.State.objects)s.Append('|').Append(o.id).Append(',').Append(o.itemId).Append(',').Append(o.x).Append(',').Append(o.z).Append(',').Append(o.rotation);foreach(var p in model.Hotel().paths)s.Append('|').Append(p.Key).Append(p.Value.style);foreach(var p in model.Hotel().plots)s.Append('|').Append(p);
 if(signature!=s.ToString()){signature=s.ToString();DisposeNode(layout);layout=Group(renderRoot,"Editable hotel");objects.Clear();rooms.Clear();effects.Clear();foreach(var r in model.State.rooms)BuildRoom(r);foreach(var o in model.State.objects)BuildObject(o);BuildPaths();BuildOwnedPlots();}
 RefreshTown();SetCutaway(!model.State.settings.exterior);SetEvening(model.State.settings.evening);if(mapChanged)FitHotel();}
 void BuildObject(ObjectState o){var d=Catalog.Find(o.itemId);if(d==null)throw new InvalidOperationException("Unknown furniture "+o.itemId);var recipe=geometry.Recipe("items",o.itemId);var root=geometry.Build(layout,recipe);HotelModel.Size(o,out float w,out float z);root.localPosition=new Vector3((o.x+w/2)*Unit,GroundY,(o.z+z/2)*Unit);root.localRotation=Quaternion.Euler(0,-o.rotation*90,0);root.name="Item_"+o.id;objects[o.id]=root;var hit=root.gameObject.AddComponent<BoxCollider>();hit.center=new Vector3(0,.5f,0);hit.size=new Vector3(d.width*Unit,1,d.depth*Unit);root.gameObject.AddComponent<WorldPick>().objectId=o.id;var fp=recipe["meta"]?["footprint"];effects[o.id]=new GodotObjectMotion(geometry,root,d.shape??d.id,fp==null?new Vector2(d.width*Unit,d.depth*Unit):new Vector2((float)fp[0],(float)fp[1]),o.id);}
 void BuildPaths(){var p=Group(layout,"Paths");foreach(var path in model.Hotel().paths){var xy=path.Key.Split(',');if(xy.Length!=2)continue;float x=float.Parse(xy[0],System.Globalization.CultureInfo.InvariantCulture),z=float.Parse(xy[1],System.Globalization.CultureInfo.InvariantCulture);string c=ConceptTheme.PathColor(path.Value.style,x,z);Box(p,new Vector3((x+.5f)*Unit,.105f,(z+.5f)*Unit),new Vector3(Unit-.028f,.1f,Unit-.028f),c);if(path.Value.style=="brick")foreach(float v in new[]{-.24f,.24f})Box(p,new Vector3((x+.5f)*Unit,.159f,(z+.5f+v)*Unit),new Vector3(Unit-.03f,.009f,.025f),Shade(c,-.1f));}Bake(p);}
 void BuildOwnedPlots(){foreach(var parcel in geometry.Map(currentMap)["parcels"]){string id=(string)parcel["id"];bool owned=id=="base"||model.Hotel().plots.Contains(id);if((bool)parcel["owned"]==owned)geometry.Build(layout,(JObject)parcel["root"]);}} void Update(){if(model==null)return;Shader.SetGlobalFloat("_PurringtonMotion",model.State.settings.motion?1:0);ReadInput();if(neighborhoods.TryGetValue(currentMap,out var neighborhood))neighborhood.SetVisitors(model);SyncActors();foreach(var effect in effects.Values)effect.Advance(Time.deltaTime,model.State.settings.motion);if(neighborhoods.TryGetValue(currentMap,out var n))n.Advance(Time.deltaTime,model.State.settings.motion);AnimateCare();SyncManager(Time.deltaTime);UpdateCamera();}
 void SyncActors(){var wanted=new HashSet<string>();var used=new HashSet<string>();foreach(var a in model.Actors){wanted.Add(a.id);bool staff=a.kind==ActorKind.Staff;int role=(a.role=="cook"||a.role=="barista")?1:a.role=="housekeeper"?2:0;if(!actors.TryGetValue(a.id,out var rig)){rig=new GodotCatRig(geometry,renderRoot,staff?"staff":a.kind==ActorKind.DayVisitor?"neighbors":"cats",(staff?role:a.kind==ActorKind.DayVisitor?a.visitorIndex%6:Math.Abs(a.catId)%18).ToString(),a.catId);rig.Root.localScale=Vector3.one*.83f;var collider=rig.Root.gameObject.AddComponent<BoxCollider>();collider.center=new Vector3(0,.6f,0);collider.size=new Vector3(.85f,1.3f,1.05f);rig.Root.gameObject.AddComponent<WorldPick>().catId=a.kind==ActorKind.Guest?a.catId:-1;var builtDrink=geometry.Build(rig.Root,geometry.Recipe("actorExtras","drink"));builtDrink.name="Milkshake";builtDrink.gameObject.SetActive(false);actors.Add(a.id,rig);}rig.Root.gameObject.SetActive(a.kind!=ActorKind.DayVisitor||(neighborhoods.TryGetValue(currentMap,out var street)&&street.IsVisitorVisible(a.visitorIndex)));var at=new Vector3(a.x*Unit,GroundY,a.z*Unit);bool walking=a.action.StartsWith("walk")||a.action=="wander";float face=a.facing;FurniturePose(a,ref at,ref face);if(staff&&role!=2)StaffDeskPose(a,rig,ref at);rig.Root.localPosition=at;rig.Root.localRotation=Quaternion.Euler(0,face*Mathf.Rad2Deg,0);rig.Advance(Time.deltaTime,model.State.settings.motion,a.action=="sunbathe"?"sleep":a.action=="sit"?"rest":a.action,walking,!string.IsNullOrEmpty(a.gesture)?a.gesture:a.action=="play"?"play_object":new[]{"dig","scratch","peek","knead","serve","handoff"}.Contains(a.action)?a.action:"",(a.gesture=="talk"||a.gesture=="happy")?a.speechElapsed:a.activityElapsed,staff,role);rig.Speech(!string.IsNullOrEmpty(a.speech)?a.speech:a.action=="order"?"One shake, please":a.action=="serve"?"Coming right up":a.action=="drink"?"mmm…":a.action=="sunbathe"?a.name+" found a sunny spot!":a.action=="sleep"?"z z z":a.action=="greet"?"Checking in":a.action=="clean"?"Fresh linens":a.action=="play"||a.action=="scratch"||a.action=="peek"?a.name+" is exploring":"");var drink=rig.Root.Find("Milkshake");if(drink)drink.gameObject.SetActive(a.action=="drink");if(!string.IsNullOrEmpty(a.venueId)&&effects.TryGetValue(a.venueId,out var fx)){fx.Activity(a.action,a.activityElapsed,a.activityToken.ToString());used.Add(a.venueId);}}
 foreach(var id in actors.Keys.Where(k=>!wanted.Contains(k)).ToArray()){DisposeNode(actors[id].Root);actors.Remove(id);}foreach(var f in effects)if(!used.Contains(f.Key))f.Value.Activity("",0,"");}
 void FurniturePose(ActorSnapshot a,ref Vector3 at,ref float face){if(a.kind==ActorKind.Staff||a.action.StartsWith("walk")||!objects.TryGetValue(a.venueId??"",out var node))return;var o=model.State.objects.FirstOrDefault(x=>x.id==a.venueId);if(o==null)return;var d=Catalog.Find(o.itemId);var occupants=model.Actors.Where(x=>x.venueId==a.venueId&&!x.action.StartsWith("walk")&&x.kind!=ActorKind.Staff).OrderBy(x=>x.catId).ToArray();int slot=Array.FindIndex(occupants,x=>x.id==a.id);Vector3 local;switch(d.shape){case "cafe_stool":local=new Vector3(0,.78f,.04f);break;case "cloud_sofa":case "lounge_sofa":case "bench":local=new Vector3((slot-(occupants.Length-1)*.5f)*.8f,.59f,d.depth*Unit*.12f);break;case "mat":case "sun_cushion":case "heated":case "blanket":case "cave":case "canopy_bed":local=new Vector3(0,.55f,d.depth*Unit*.11f);break;case "perch":local=new Vector3(0,1.05f,.06f);break;case "picnic":local=new Vector3(d.width*Unit*.32f*(slot<2?-1:1),.26f,d.depth*Unit*.32f*(slot%2==0?-1:1));break;case "table":local=new Vector3((slot/2-(Mathf.Ceil(occupants.Length/2f)-1)*.5f)*.8f,.5f,d.depth*Unit*.4f*(slot%2==0?-1:1));break;default:return;}at=ToAuthored(node.TransformPoint(local));face=-o.rotation*Mathf.PI/2;}
 public void SetPlacementPreview(string id,Vector3 position,int rotation,bool valid){var d=Catalog.Find(id);float w=d?.width??4,z=d?.depth??3;if(rotation%2!=0){float t=w;w=z;z=t;}PreviewOutline(position,w,z,valid);}
 public void SetRoomPlacementPreview(int width,int depth,Vector3 position,int rotation,bool valid){PreviewOutline(position,width,depth,valid);}
 void PreviewOutline(Vector3 pos,float w,float d,bool valid){ClearPreview();preview=Group(renderRoot,"Placement preview");preview.localPosition=new Vector3(pos.x*Unit,.23f,pos.z*Unit);w*=Unit;d*=Unit;string c=valid?"60D6A6":"FFAB97";foreach(float x in new[]{0,w})Box(preview,new Vector3(x,.08f,d/2),new Vector3(.065f,.15f,d),c);foreach(float z in new[]{0,d})Box(preview,new Vector3(w/2,.08f,z),new Vector3(w,.15f,.065f),c);}
 public void ClearPreview(){DisposeNode(preview);preview=null;}
 static Transform Group(Transform parent,string name){var t=new GameObject(name).transform;t.SetParent(parent,false);return t;}static void DisposeNode(Transform t){if(t){t.gameObject.SetActive(false);Destroy(t.gameObject);}}static Color Hex(string c){ColorUtility.TryParseHtmlString(c.StartsWith("#")?c:"#"+c,out var v);return v;}static string Shade(string c,float f){var v=Hex(c);v=f>=0?Color.Lerp(v,Color.white,f):v*(1+f);return ColorUtility.ToHtmlStringRGB(v);}
 void Box(Transform p,Vector3 at,Vector3 size,string color){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name="Voxel";g.transform.SetParent(p,false);g.transform.localPosition=at;g.transform.localScale=size;g.GetComponent<Collider>().enabled=false;Destroy(g.GetComponent<Collider>());g.GetComponent<MeshRenderer>().sharedMaterial=geometry.Material(color);}
 void Bake(Transform root){var groups=new Dictionary<Material,List<CombineInstance>>();var old=new List<GameObject>();foreach(var f in root.GetComponentsInChildren<MeshFilter>()){var r=f.GetComponent<MeshRenderer>();if(!r||f.GetComponent<TextMesh>())continue;if(!groups.TryGetValue(r.sharedMaterial,out var list))groups[r.sharedMaterial]=list=new List<CombineInstance>();list.Add(new CombineInstance{mesh=f.sharedMesh,transform=root.worldToLocalMatrix*f.transform.localToWorldMatrix});old.Add(f.gameObject);}foreach(var g in groups){var t=Group(root,"Batched cuboids");var mesh=new Mesh{indexFormat=IndexFormat.UInt32};mesh.CombineMeshes(g.Value.ToArray());t.gameObject.AddComponent<MeshFilter>().sharedMesh=mesh;t.gameObject.AddComponent<MeshRenderer>().sharedMaterial=g.Key;t.gameObject.AddComponent<GeneratedVoxelMesh>().OwnedMesh=mesh;}foreach(var g in old){g.SetActive(false);Destroy(g);}}
}
public sealed class GeneratedVoxelMesh:MonoBehaviour{public Mesh OwnedMesh;void OnDestroy(){if(OwnedMesh)Destroy(OwnedMesh);}}
public sealed class WorldPick:MonoBehaviour{public int catId=-1;public string objectId;}
}









