using System.Collections.Generic;using System.Linq;using NUnit.Framework;using Newtonsoft.Json.Linq;using Purrington.Presentation;
namespace Purrington.Tests {
public sealed class LawnColorTests {
 static IEnumerable<string> Colors(JToken recipe){return recipe.SelectTokens("..parts[*].color").Select(c=>(string)c);}
 [Test]public void LawnColorIsTheWorldGroundSwatch(){using(var g=new GodotGeometry()){Assert.AreEqual("#83a36eff",GodotGeometry.LawnColor((JObject)g.Map(0)["groundWithoutParcels"]));Assert.AreEqual("#cfbb90ff",GodotGeometry.LawnColor((JObject)g.Map(1)["groundWithoutParcels"]));Assert.AreEqual("#758c64ff",GodotGeometry.LawnColor((JObject)g.Map(2)["groundWithoutParcels"]));Assert.AreEqual("#c2cdcbff",GodotGeometry.LawnColor((JObject)g.Map(3)["groundWithoutParcels"]));}}
 [Test]public void OwnedParcelLawnMatchesWorldGroundOnEveryMap(){using(var g=new GodotGeometry())for(int i=0;i<4;i++){var map=g.Map(i);string lawn=GodotGeometry.LawnColor((JObject)map["groundWithoutParcels"]);foreach(var parcel in map["parcels"].Where(p=>(bool)p["owned"])){var colors=Colors(GodotGeometry.Recolor((JObject)parcel["root"],lawn)).ToArray();Assert.IsNotEmpty(colors,"map "+i+" parcel "+parcel["id"]+" has lawn parts");foreach(string c in colors)Assert.AreEqual(lawn,c,"map "+i+" parcel "+parcel["id"]);Assert.AreEqual(g.Material(lawn).color,g.Material(colors[0]).color,"shared material color");}}}
 [Test]public void RecolorLeavesTheAuthoredRecipeUntouched(){using(var g=new GodotGeometry()){var root=(JObject)g.Map(0)["parcels"].First(p=>(bool)p["owned"])["root"];string before=root.ToString();GodotGeometry.Recolor(root,"#000000ff");Assert.AreEqual(before,root.ToString());}}
 [Test]public void OwnedSlabsAreHiddenButUnownedSaleCuesRemain(){using(var g=new GodotGeometry())for(int i=0;i<4;i++){foreach(var parcel in g.Map(i)["parcels"]){var root=(JObject)parcel["root"];if((bool)parcel["owned"]){Assert.AreEqual(1,Colors(root).Count(),"owned parcel should only contain its redundant lawn slab");Assert.IsNull(GodotGeometry.VisibleParcel((JObject)parcel,true),"map "+i+" "+parcel["id"]);}else{Assert.AreSame(root,GodotGeometry.VisibleParcel((JObject)parcel,false),"map "+i+" "+parcel["id"]);Assert.Greater(Colors(root).Count(),1,"for-sale parcel keeps sign and stakes");}}}}
}
}
