using System;using System.Collections.Generic;using System.IO;using System.Linq;using NUnit.Framework;using Newtonsoft.Json;using Newtonsoft.Json.Linq;using Purrington.Domain;using UnityEngine;
namespace Purrington.Tests {
public sealed class MeadowEditModeTests {
 ParityContent Content()=>ParityContent.LoadJson(Resources.Load<TextAsset>("Content/GodotReference").text);
 sealed class MemoryStore:ISaveStore{public bool fail;public HotelState saved;public HotelState Load()=>saved==null?null:HotelModel.Copy(saved);public bool Save(HotelState s){if(fail)return false;saved=HotelModel.Copy(s);return true;}}
 HotelModel Model(MemoryStore store=null){var m=new HotelModel(store??new MemoryStore(),Content());Assert.IsTrue(m.LoadOrCreate().success);return m;}
 [Test]public void ReferenceContentIncludesFourMapsSixArrangementsAndAllCats(){var m=Model();Assert.AreEqual(38,Catalog.All.Length);Assert.AreEqual(6,m.Content.Templates.Length);Assert.AreEqual(4,m.State.hotels.Count);Assert.AreEqual(18,m.State.cats.Count);Assert.AreEqual(4,m.GuestCapacity());Assert.AreEqual(64,m.Rate());}
 [Test]public void EveryArrangementSupportsEveryRotation(){foreach(var template in Content().Templates)for(int r=0;r<4;r++){var m=Model();m.SetGodMode(true);m.Hotel().rooms.Clear();m.Hotel().objects.Clear();var bounds=m.Map()["base"];var result=m.Execute("place_template",new JObject{{"template",template["id"]},{"x",(int)bounds[0]+2},{"y",(int)bounds[1]+2},{"rotation",r}});Assert.IsTrue(result.success,template["id"]+" "+r+": "+result.message);Assert.AreEqual(template["objects"].Count(),m.State.objects.Count);}}
 [Test]public void QuotesAndFailedSavesAreTransactional(){var store=new MemoryStore();var m=Model(store);string before=JsonConvert.SerializeObject(m.State);m.Quote("upgrade",JObject.Parse("{service:0}"));Assert.AreEqual(before,JsonConvert.SerializeObject(m.State));store.fail=true;Assert.IsFalse(m.Execute("upgrade",JObject.Parse("{service:0}")).success);Assert.AreEqual(before,JsonConvert.SerializeObject(m.State));}
 [Test]public void FavoriteCareCooldownAndUndoPreserveProgress(){var m=Model();m.Care(0,m.State.cats[0].favoriteAction);Assert.AreEqual(6,m.State.cats[0].bond);m.Care(0,"brush");Assert.AreEqual(6,m.State.cats[0].bond);double coins=m.State.coins;Assert.IsTrue(m.Execute("upgrade",JObject.Parse("{service:0}")).success);m.State.coins+=13;Assert.IsTrue(m.Undo().success);Assert.AreEqual(coins+13,m.State.coins);Assert.AreEqual(6,m.State.cats[0].bond);}
 [Test]public void DictionarySaveRoundTripRetainsAllDestinations(){var m=Model();var codec=new NewtonsoftSaveCodec();var restored=codec.Deserialize(codec.Serialize(m.State));Assert.IsTrue(HotelModel.Valid(restored));for(int i=0;i<4;i++){Assert.AreEqual(m.Hotel(i).paths.Count,restored.hotels[i].paths.Count);Assert.AreEqual(m.Hotel(i).objects.Count,restored.hotels[i].objects.Count);}}
 [Test]public void AuthoritativeLifeMovesSafelyAndCompletesVisits(){var m=Model();for(int step=0;step<3000;step++){m.Tick(.2f);foreach(var a in m.Actors){Assert.IsTrue(m.CanWalk(a.x,a.z),a.name);foreach(var b in m.Actors.Where(b=>String.CompareOrdinal(b.id,a.id)>0))Assert.GreaterOrEqual(new LotPoint(a.x,a.z).Distance(new LotPoint(b.x,b.z)),.719f);}}Assert.Greater(m.Hotel().visits,0);}
 [Test]public void GodModeAndOfflineClaimRollback(){var store=new MemoryStore();var m=Model(store);Assert.IsTrue(m.SetGodMode(true).success);Assert.IsTrue(m.State.hotels.All(h=>h.owned));Assert.IsTrue(m.State.cats.All(c=>c.known));m.State.lastSeen=1000;double rate=m.Rate();m.Reconcile(41000);Assert.AreEqual(rate*480,m.State.pendingCoins,.001);double pending=m.State.pendingCoins;store.fail=true;Assert.IsFalse(m.ClaimOffline().success);Assert.AreEqual(pending,m.State.pendingCoins);}
 [Test]public void ExclusiveBarStaffAndGuestSlots(){var m=Model();m.SetGodMode(true);m.Hotel().rooms.Clear();m.Hotel().objects.Clear();m.Hotel().paths.Clear();for(int x=-12;x<12;x++)for(int z=-12;z<12;z++)m.Hotel().paths[x+","+z]=new PathState{style="earth",paid=0};Assert.IsTrue(m.Execute("place_room",new JObject{{"kind","shared"},{"name","Facing counters"},{"x",-5},{"y",-5},{"w",10},{"h",10}}).success);Assert.IsTrue(m.Execute("place_object",new JObject{{"item","milkshake_counter"},{"x",0},{"y",0},{"rotation",0}}).success);Assert.IsTrue(m.Execute("place_object",new JObject{{"item","milkshake_counter"},{"x",0},{"y",-1.5},{"rotation",2}}).success);var staff=new HashSet<string>();foreach(var v in m.Venues().Where(v=>v.open&&v.role=="bar")){Assert.IsNotNull(v.staffSlot,"open bar needs staffSlot");Assert.IsFalse(staff.Contains(v.staffSlot.key),"staff slots unique");staff.Add(v.staffSlot.key);}Assert.Greater(staff.Count,0);foreach(var v in m.Venues())foreach(var s in v.slots)Assert.IsFalse(staff.Contains(s.key),"guest slot must not reuse staff key");m.Tick(1f);var used=new HashSet<string>();foreach(var a in m.Actors){if(string.IsNullOrEmpty(a.slot))continue;Assert.IsFalse(used.Contains(a.slot),a.slot);used.Add(a.slot);}}
 [Test]public void CopiedCountersDoNotMultiplyUpgradeIncome(){var m=Model();m.SetGodMode(true);m.Hotel().rooms.Clear();m.Hotel().objects.Clear();m.Hotel().paths.Clear();for(int x=-12;x<12;x++)for(int z=-12;z<12;z++)m.Hotel().paths[x+","+z]=new PathState{style="earth",paid=0};Assert.IsTrue(m.Execute("place_room",new JObject{{"kind","shared"},{"name","Facing counters"},{"x",-5},{"y",-5},{"w",10},{"h",10}}).success);Assert.IsTrue(m.Execute("place_object",new JObject{{"item","milkshake_counter"},{"x",0},{"y",0},{"rotation",0}}).success);Assert.IsTrue(m.Execute("place_object",new JObject{{"item","milkshake_counter"},{"x",0},{"y",-1.5},{"rotation",2}}).success);double rate=m.Rate();var counter=m.Hotel().objects.Last(o=>o.itemId=="milkshake_counter");Assert.IsTrue(m.Execute("store_object",new JObject{{"id",counter.id}}).success);Assert.AreEqual(rate,m.Rate());}
 [Test]public void ReceptionRemovalDropsCapacityAndReleasesReservations(){var m=Model();Assert.AreEqual(4,m.GuestCapacity());for(int i=0;i<250;i++){m.Tick(.2f);if(m.Actors.Any(a=>a.catId<1000&&!string.IsNullOrEmpty(a.slot)))break;}Assert.IsTrue(m.Actors.Any(a=>a.catId<1000&&!string.IsNullOrEmpty(a.slot))||m.Reservations.Count>0);int visits=m.Hotel().visits;var reception=m.Hotel().objects.First(o=>o.itemId=="reception_counter");Assert.IsTrue(m.Execute("store_object",new JObject{{"id",reception.id}}).success);Assert.AreEqual(0,m.GuestCapacity());m.Tick(.2f);Assert.IsTrue(m.Actors.Count(a=>a.catId<1000)==0||m.Actors.Where(a=>a.catId<1000).All(a=>string.IsNullOrEmpty(a.slot)));Assert.AreEqual(visits,m.Hotel().visits);Assert.IsTrue(m.Execute("retrieve_object",new JObject{{"id",reception.id},{"x",-3},{"y",-2},{"rotation",0}}).success);Assert.AreEqual(4,m.GuestCapacity());}
 [Test]public void OutdoorBenchOpensOnGrass(){var m=Model();Assert.IsTrue(m.Execute("place_object",new JObject{{"item","bench"},{"x",-6},{"y",10.5},{"rotation",0}}).success);var id=m.Hotel().objects.Last(o=>o.itemId=="bench").id;var venue=m.Venues().FirstOrDefault(v=>v.id==id);Assert.IsNotNull(venue);Assert.IsTrue(venue.open);}
 [Test]public void GuestIntentReadableDuringMilkshake(){var m=Model();ActorSnapshot hit=null;for(float t=0;t<60&&hit==null;t+=.2f){m.Tick(.2f);hit=m.Actors.FirstOrDefault(a=>a.catId<1000&&(a.action=="order"||a.action=="wait"||a.action=="drink"||a.phase=="order"||a.phase=="serve"));}Assert.IsNotNull(hit,"expected milkshake order/serve/drink within 60s");Assert.IsFalse(string.IsNullOrEmpty(hit.intent));StringAssert.IsMatch("(?i)milkshake|order|seat|drink|wait|heading|finding",hit.intent);}
}
}
