using System;using System.IO;using System.Linq;using NUnit.Framework;using Newtonsoft.Json;using Newtonsoft.Json.Linq;using Purrington.Domain;using UnityEngine;
namespace Purrington.Tests {
public sealed class MeadowEditModeTests {
 ParityContent Content()=>ParityContent.LoadJson(Resources.Load<TextAsset>("Content/GodotReference").text);
 sealed class MemoryStore:ISaveStore{public bool fail;public HotelState saved;public HotelState Load()=>saved==null?null:HotelModel.Copy(saved);public bool Save(HotelState s){if(fail)return false;saved=HotelModel.Copy(s);return true;}}
 HotelModel Model(MemoryStore store=null){var m=new HotelModel(store??new MemoryStore(),Content());Assert.IsTrue(m.LoadOrCreate().success);return m;}
 [Test]public void ReferenceContentIncludesFourMapsSixArrangementsAndAllCats(){var m=Model();Assert.AreEqual(38,Catalog.All.Length);Assert.AreEqual(6,m.Content.Templates.Length);Assert.AreEqual(4,m.State.hotels.Count);Assert.AreEqual(18,m.State.cats.Count);Assert.AreEqual(4,m.GuestCapacity());Assert.AreEqual(64,m.Rate());}
 [Test]public void EveryArrangementSupportsEveryRotation(){foreach(var template in Content().Templates)for(int r=0;r<4;r++){var m=Model();m.SetGodMode(true);m.Hotel().rooms.Clear();m.Hotel().objects.Clear();var bounds=m.Map()["base"];var result=m.Execute("place_template",new JObject{{"template",template["id"]},{"x",(int)bounds[0]+2},{"y",(int)bounds[1]+2},{"rotation",r}});Assert.IsTrue(result.success,template["id"]+" "+r+": "+result.message);Assert.AreEqual(template["objects"].Count(),m.State.objects.Count);}}
 [Test]public void QuotesAndFailedSavesAreTransactional(){var store=new MemoryStore();var m=Model(store);string before=JsonConvert.SerializeObject(m.State);m.Quote("upgrade",JObject.Parse("{service:0}"));Assert.AreEqual(before,JsonConvert.SerializeObject(m.State));store.fail=true;Assert.IsFalse(m.Execute("upgrade",JObject.Parse("{service:0}")).success);Assert.AreEqual(before,JsonConvert.SerializeObject(m.State));}
 [Test]public void FavoriteCareCooldownAndUndoPreserveProgress(){var m=Model();m.Care(0,m.State.cats[0].favoriteAction);Assert.AreEqual(6,m.State.cats[0].bond);m.Care(0,"brush");Assert.AreEqual(6,m.State.cats[0].bond);double coins=m.State.coins;Assert.IsTrue(m.Execute("upgrade",JObject.Parse("{service:0}")).success);m.State.coins+=13;Assert.IsTrue(m.Undo().success);Assert.AreEqual(coins+13,m.State.coins);Assert.AreEqual(6,m.State.cats[0].bond);}
 [Test]public void DictionarySaveRoundTripRetainsAllDestinations(){var m=Model();var codec=new NewtonsoftSaveCodec();var restored=codec.Deserialize(codec.Serialize(m.State));Assert.IsTrue(HotelModel.Valid(restored));for(int i=0;i<4;i++){Assert.AreEqual(m.Hotel(i).paths.Count,restored.hotels[i].paths.Count);Assert.AreEqual(m.Hotel(i).objects.Count,restored.hotels[i].objects.Count);}}
 [Test]public void AuthoritativeLifeMovesSafelyAndCompletesVisits(){var m=Model();for(int step=0;step<3000;step++){m.Tick(.2f);foreach(var a in m.Actors){Assert.IsTrue(m.CanWalk(a.x,a.z),a.name);foreach(var b in m.Actors.Where(b=>String.CompareOrdinal(b.id,a.id)>0))Assert.GreaterOrEqual(new LotPoint(a.x,a.z).Distance(new LotPoint(b.x,b.z)),.719f);}}Assert.Greater(m.Hotel().visits,0);}
 [Test]public void GodModeAndOfflineClaimRollback(){var store=new MemoryStore();var m=Model(store);Assert.IsTrue(m.SetGodMode(true).success);Assert.IsTrue(m.State.hotels.All(h=>h.owned));Assert.IsTrue(m.State.cats.All(c=>c.known));m.State.lastSeen=1000;double rate=m.Rate();m.Reconcile(41000);Assert.AreEqual(rate*480,m.State.pendingCoins,.001);double pending=m.State.pendingCoins;store.fail=true;Assert.IsFalse(m.ClaimOffline().success);Assert.AreEqual(pending,m.State.pendingCoins);}
 [Test]public void IncomeAndArrivalReadoutsTrackActorsAndRate(){var m=Model();m.Tick(1.5f);Assert.Greater(m.Rate(),0);Assert.GreaterOrEqual(m.Actors.Count(a=>a.catId<1000),0);Assert.LessOrEqual(m.Actors.Count(a=>a.catId<1000),m.GuestCapacity());var staying=m.Actors.Count(a=>a.catId<1000);var arriving=m.Actors.Count(a=>a.catId<1000&&!a.checkedIn);Assert.GreaterOrEqual(staying,arriving);}
}
}
